// ART-BOSS-4 Kling 프롬프트 (서리 여왕 이자벨라 b_frostqueen · 사신 데스 b_death)
// 모델 kling-image-v3_0_omni · image_to_image · img_resolution 2k. 图片1 = 보스 초상화 (assets/portraits/<id>.webp → PNG 업로드).
// 템플릿: docs/art/BOSS_PIPELINE.md §3 (스타일 문구를 맨 앞에, 평평한 중간 회색 배경 + 왼쪽 위 키라이트 공통 꼬리말).
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_art-boss-4.json 과 configs/<id>.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/art-boss-4.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';

const FQ = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, pale icy blues, frost white and cold teal with deep navy shadows, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const DT = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, aged yellowed ivory bone, black and charcoal cloth, eerie pale green soul fire, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const NOFX = 'No snow, no mist, no smoke, no particles, no magic effects around the object.';

/** shot → { boss, aspect, count, refs (image_1 = 초상화), prompt } */
export const SHOTS = {
  // ───────── 서리 여왕 이자벨라 ─────────
  fq_head_a: { boss: 'b_frostqueen', aspect: '1:1', count: 2, prompt: `${FQ} The head and long neck of the ice queen from 图片1 alone, in strict side view (profile) facing right. Gaunt hollow-cheeked face with deathly pale blue-white skin cracked like frozen porcelain, dark blue frost veins spreading from the eyes down the cheek, glowing pale cyan eyes without pupils, a thin cruel smile with dark blue lips, a tall crown of long jagged icicle spikes fused into the skull and rising high above the head, long white hair swept back and falling behind the head down to the nape. The neck is cut cleanly and straight at its base. No shoulders, no body, no hands. ${NOFX} ${SUFFIX}` },
  fq_head_b: { boss: 'b_frostqueen', aspect: '1:1', count: 1, refs: ['portrait', 'fq_head_a'], prompt: `${FQ} The same head as 图片2 (same crown, hair, skin and colours), strict side view (profile) facing right, but now screaming in monstrous rage: the lower jaw unnaturally unhinged and dropped far down like a snake, the mouth split wide open showing rows of long sharp translucent ice fangs and a black frozen throat, the eyes blazing bright white-cyan, frost cracks spreading across the whole face. The neck is cut cleanly and straight at its base. No shoulders, no body, no hands. ${NOFX} ${SUFFIX}` },
  fq_torso: { boss: 'b_frostqueen', aspect: '3:4', count: 2, prompt: `${FQ} The upper body (torso only) of the ice queen from 图片1, strict side view facing right: bony bare shoulders and sharp collarbones, a short neck stump cut cleanly at the top, a tight corset bodice of jagged translucent blue ice plates and white frost lace, emaciated ribs showing through translucent icy skin on the side, a glowing cold-blue frozen heart crystal inside the chest, the narrow waist cut cleanly and straight at the bottom. No arms (the shoulders end in rounded stumps), no head, no skirt, no hands. ${NOFX} ${SUFFIX}` },
  fq_arm: { boss: 'b_frostqueen', aspect: '4:3', count: 1, prompt: `${FQ} Three separate pieces of the arm of the ice queen from 图片1, laid out apart from each other in three horizontal rows with wide empty space between them, each piece lying straight and horizontal, pointing right: 1) an upper arm from shoulder to elbow inside a torn translucent frost-lace sleeve, 2) a thin bony forearm with its hand attached, the very long skeletal fingers spread wide like claws ending in long sharp icicle nails, palm open, 3) another thin forearm with its hand, the long fingers curled into a grasping claw with icicle nails. Pale blue-white skin cracked like porcelain, blue frost veins. ${NOFX} ${SUFFIX}` },
  fq_skirt: { boss: 'b_frostqueen', aspect: '3:4', count: 2, prompt: `${FQ} The lower half of the ice queen's gown from 图片1 alone, strict side view facing right: a huge bell-shaped skirt made of layered jagged translucent blue ice and frozen white lace, from the narrow waist at the top centre to a wide ragged hem of hanging icicles at the bottom. Grotesque: several frozen human victims are trapped inside the ice of the skirt — pale screaming human faces pressed against the inside of the ice with open mouths and empty eyes, and two thin frozen human hands pushing out through the ice surface. The waist is cut cleanly and straight at the top. No torso, no legs, no feet. ${NOFX} ${SUFFIX}` },
  fq_collar: { boss: 'b_frostqueen', aspect: '4:3', count: 1, prompt: `${FQ} A huge fan-shaped standing collar made of long jagged ice blades, belonging to the ice queen of 图片1, seen from the side as a flat half-circle fan: about twelve long translucent icicle blades of different lengths radiating upward and outward from a single root point at the bottom centre of the image, like a frozen halo or crystalline wings, cold blue light glowing inside the ice. Only the collar, no person. ${NOFX} ${SUFFIX}` },
  fq_victims: { boss: 'b_frostqueen', aspect: '16:9', count: 1, prompt: `${FQ} Four separate grotesque frozen corpse parts from the ice palace of 图片1, standing upright in one row with wide empty space between them, no piece touches another: 1) a thin frozen human arm reaching straight up with clawing fingers, encased in cracked blue ice, 2) a second frozen human arm bent at the elbow, reaching up, 3) a frozen screaming human head covered in frost and small icicles, 4) a frozen skeletal hand with icicle fingers reaching up. Each piece has a flat cut base at the bottom. ${NOFX} ${SUFFIX}` },
  fq_shards: { boss: 'b_frostqueen', aspect: '16:9', count: 1, prompt: `${FQ} About ten separate sharp broken ice shards and crystal fragments of varied sizes from 图片1, arranged in a loose grid with wide empty space between pieces, no piece touches another: jagged translucent blue-white ice splinters, long thin icicle splinters and a few thick broken crystal chunks with frost inside. ${NOFX} ${SUFFIX}` },
  fq_hazard: { boss: 'b_frostqueen', aspect: '16:9', count: 1, prompt: `${FQ} Three separate ice objects from 图片1 laid out left to right with wide empty space between them, no piece touches another: 1) a tall jagged ice crystal pillar standing upright on a flat base at the bottom, a cluster of smaller crystals at its foot and a sharp pointed top, 2) a long sharp icicle hanging straight down, thick at the top and pointed at the bottom, 3) a tall upright cluster of sharp ice spikes growing from a flat base. Translucent blue-white ice with frost inside and bright cold highlights. ${NOFX} ${SUFFIX}` },
  fq_cape_tex: { boss: 'b_frostqueen', aspect: '1:1', count: 1, prompt: `Paint in exactly the same painterly style as 图片1. A flat rectangular swatch of the ice queen's cape fabric from 图片1 seen straight on and evenly lit, filling the whole image edge to edge: translucent pale blue silk with fine white frost-lace patterns, tiny ice crystals and faint darker blue folds, seamless tileable texture, no person, no object, no background, no text.` },

  // ───────── 사신 데스 ─────────
  dt_hood: { boss: 'b_death', aspect: '4:3', count: 2, prompt: `${DT} The hooded skull head of the grim reaper from 图片1 alone, strict side view (profile) facing right: a deep ragged black hood framing a cracked yellowed human skull, the mouth wide open showing all the teeth, the lower jaw clearly separate and dropped open at the hinge with a dark gap behind it, empty eye sockets burning with pale green soul fire, a few small bones and teeth sewn into the torn edge of the hood. The hood ends at the neck. No body, no hands, no scythe. ${NOFX} ${SUFFIX}` },
  dt_torso: { boss: 'b_death', aspect: '3:4', count: 2, prompt: `${DT} The upper body of the grim reaper from 图片1 alone, strict side view facing right: a tattered black cloak draped over bony shoulders with a spiky mantle of black feathers and bone spikes, the front of the cloak torn open to show the yellowed ribcage and spine with pale green soul fire burning inside the ribs, a string of small skulls hanging across the chest. No arms (the shoulders end in cloth), no head (an empty neck opening at the top), cut straight across at the hips at the bottom. ${NOFX} ${SUFFIX}` },
  dt_arm: { boss: 'b_death', aspect: '4:3', count: 1, prompt: `${DT} Four separate skeletal arm pieces of the grim reaper from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) an upper arm bone (humerus) lying horizontal, 2) a forearm (radius and ulna together) lying horizontal, 3) a bony skeletal hand clenched in a tight fist around an empty round hole as if gripping a pole, 4) a bony skeletal hand wide open with long clawed fingers spread. Old cracked yellowed bone. ${NOFX} ${SUFFIX}` },
  dt_scythe: { boss: 'b_death', aspect: '21:9', count: 1, prompt: `${DT} The scythe of the grim reaper from 图片1 taken apart into two separate pieces with wide empty space between them: 1) at the bottom, the long straight shaft lying perfectly horizontal across almost the whole image width, made of dark ancient wood wrapped in fused human vertebrae and bone rings, a small skull capping the right end, 2) at the top, the huge curved crescent scythe blade alone, dark pitted steel with a bright honed cutting edge, bone spikes along the back of the blade and a skull ornament at the tang on the left. ${NOFX} ${SUFFIX}` },
  dt_skull2: { boss: 'b_death', aspect: '4:3', count: 2, prompt: `${DT} The giant horned skull of the grim reaper's true demonic form from 图片1, strict side view (profile) facing right, the mouth wide open showing both rows of long sharp teeth and the dark throat, the lower jaw clearly separate at the hinge, two long curved black horns sweeping back from the cranium, deep cracks across the skull with pale green soul fire leaking out of the cracks and the eye sockets. Only the skull, no neck, no body. ${NOFX} ${SUFFIX}` },
  dt_rib2: { boss: 'b_death', aspect: '3:4', count: 2, prompt: `${DT} The giant skeletal torso of the grim reaper's true demonic form from 图片1 alone, strict side view facing right: a huge yellowed ribcage on a thick spine with a pelvis at the bottom, a blazing pale green soul-fire heart inside the ribs with tormented screaming ghost faces trapped in the flames, burnt black cloak rags hanging from the shoulders and the spine, bone spikes on the shoulder blades. No head (the neck vertebrae end at the top), no arms, no legs. ${NOFX} ${SUFFIX}` },
  dt_wing: { boss: 'b_death', aspect: '4:3', count: 1, prompt: `${DT} A single huge skeletal bone wing of the grim reaper's true demonic form from 图片1, spread wide: long yellowed bone fingers fanning out from the root at the lower left to the tips at the upper right, a torn tattered black membrane with ragged holes stretched between the bones, faint pale green soul-fire glow along the membrane edges. Only the wing. ${NOFX} ${SUFFIX}` },
  dt_souls: { boss: 'b_death', aspect: '16:9', count: 1, prompt: `${DT} Four separate screaming ghost souls from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: each one is a pale glowing green translucent wisp with a tormented screaming human face at the front on the right and a long flowing ghostly tail trailing away to the left. ${SUFFIX}` },
  dt_debris: { boss: 'b_death', aspect: '16:9', count: 1, prompt: `${DT} About nine separate broken bone fragments of the grim reaper from 图片1, arranged in a loose grid with wide empty space between pieces, no piece touches another: skull shards, broken curved ribs, single vertebrae, a snapped long bone, and one tall jagged bone spike standing upright on its flat base. ${NOFX} ${SUFFIX}` },
  dt_cloak_tex: { boss: 'b_death', aspect: '1:1', count: 1, prompt: `Paint in exactly the same painterly style as 图片1. A flat rectangular swatch of the grim reaper's cloak cloth from 图片1 seen straight on and evenly lit, filling the whole image edge to edge: ragged black and charcoal wool with a faint dark green sheen, worn threadbare texture with small tears, seamless tileable texture, no person, no object, no background, no text.` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || k === id) console.log(`\n# ${k} (${s.boss}, ${s.aspect}, ×${s.count})\n${s.prompt}`);
}
