// ART-BOSS-7 Kling 프롬프트 (2부 보스: 지즈 b_ziz · 마라 b_mara · 베헤모스 b_behemoth)
// 모델 kling-image-v3_0_omni · image_to_image · img_resolution 2k. 图片1 = 보스 초상화 (assets/portraits/<id>.webp → PNG 업로드).
// 템플릿: docs/art/BOSS_PIPELINE.md §3 (스타일 문구를 맨 앞에, 평평한 중간 회색 배경 + 왼쪽 위 키라이트 공통 꼬리말).
// 퍼핏 방향: 지즈 = 정면 몸통(날개 좌우 대칭) + 옆모습 머리(오른쪽을 봄) · 마라 = 옆모습(오른쪽을 봄) · 베헤모스 = 옆모습(오른쪽을 봄).
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_art-boss-7.json 과 configs/<id>.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/art-boss-7.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No smoke, no mist, no clouds, no fire, no sparks, no lightning bolts, no particles, no glow haze, no magic effects around the object.';
/** v2 (지즈 재생성): 첫 묶음에서 "rim light" 문구가 물체 둘레에 하늘색 발광 테를 만들었다 → 매트가 테를 남긴다. 둘레 발광 금지 문구 추가 */
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';

const ZZ = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, storm-grey and blue-black feathers with subtle cold highlights, weathered ivory bone, wet dark red flesh, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const MR = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, sickly grey-mauve emaciated skin, cracked yellowed white porcelain, rusted black wrought iron, dried blood, faded violet and dusty rose tones, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const BH = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, rotting mossy grey-brown hide like tree bark with patchy fur, weathered ivory bone, wet dark red flesh, pale sickly mushrooms with faint green bioluminescence, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';

/** shot → { boss, aspect, count, refs (image_1 = 초상화, 그 뒤 = 이미 채택한 결과), prompt } */
export const SHOTS = {
  // ───────── 지즈 (폭풍을 부르는 거신조) — 图片1 = portraits/b_ziz ─────────
  zz_head: { boss: 'b_ziz', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${ZZ} Strict side view (profile) of the head of the giant storm bird from 图片1 alone, facing right: a huge weathered bird skull with a long cruel hooked beak, the beak wide open, the lower mandible clearly separate and dropped open at the hinge with a dark empty gap and a dark red throat between upper and lower beak, serrated bone edges like teeth along both beak halves, a deep empty eye socket, cracks and old scars in the bone, a shaggy crest of ragged storm-dark feathers on the back of the skull, the feathered neck cut flat at the lower left. ${NOFX} ${SUFFIX}` },
  zz_torso: { boss: 'b_ziz', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${ZZ} The torso of the giant storm bird from 图片1 WITHOUT head, WITHOUT wings and WITHOUT legs, seen straight from the front, symmetric: a massive barrel chest covered in shaggy layered storm-grey and blue-black feathers, the middle of the chest torn open by a huge tall oval wound with ragged torn feather edges and wet dark red flesh inside, the wound is an empty dark red hollow (no ribs, no bones inside it), a spiky collar ruff of long feathers around the neck stump at the top, ragged feather fringes hanging at the bottom, flat cut neck stump at the top middle. ${NOFX} ${SUFFIX}` },
  zz_ribs: { boss: 'b_ziz', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${ZZ} Two separate bone pieces laid apart with wide empty space between them: 1) the left half of a giant bird ribcage seen from the front: five long curved weathered ivory ribs attached at their top-right ends to a short vertical bone spine piece, curving down and outward to the left like claws, cracked, with shreds of dark red flesh; 2) a single long narrow bird breastbone keel, vertical, pale ivory with a sharp ridge. ${NOFX} ${SUFFIX}` },
  zz_wingarm: { boss: 'b_ziz', aspect: '21:9', count: 2, refs: ['portrait'], prompt: `${ZZ} A single long bony wing arm of the storm bird from 图片1 lying perfectly straight and level across the whole image width with empty margin at both ends, strict side view: from the shoulder stump on the left to the pointed wing tip on the right, three long bones of about equal length joined end to end at a knobbly elbow and a knobbly wrist with sharp bone spurs, grey-black feathered skin stretched over the bones, the pale ivory bone ridge exposed along the whole top edge, a thick band of short overlapping dark covert feathers hanging below the bones along the whole length. No long flight feathers. ${NOFX} ${SUFFIX}` },
  zz_feathers: { boss: 'b_ziz', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${ZZ} Five separate long bird flight feathers of the storm bird from 图片1 laid perfectly horizontal one above another with wide empty space between them, no feather touches another, the quill root on the left and the tip on the right: dark storm-grey and blue-black vanes with a pale central shaft and cold pale-blue rim light, different shapes: two long narrow primary feathers, two broad secondary feathers, one ragged torn feather with a chunk bitten out of it. ${NOFX} ${SUFFIX}` },
  zz_eyes: { boss: 'b_ziz', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${ZZ} Three separate objects in one row with wide empty space between them, no piece touches another: 1) a single large open demon eye embedded in a lump of wrinkled grey-black flesh with thick puffy eyelids, a glowing pale yellow-white iris with a vertical black slit pupil, bloodshot white; 2) the same fleshy lump with the eye closed, the eyelids sewn shut with crude black stitches; 3) the same fleshy lump with the eye burst open, a torn bloody ruptured socket with shredded eyelids, dark blood. All three the same size, horizontal almond shape. ${NOFX} ${SUFFIX}` },
  zz_leg: { boss: 'b_ziz', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${ZZ} Four separate leg pieces of the storm bird from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) a thick shaggy thigh covered in ragged storm-grey feathers, vertical, 2) a long vertical scaly shin like a cracked grey stone spire bound with two tarnished gold bands, 3) a huge bird foot with three long hooked black talons like broken stone spikes, toes spread wide open pointing down, 4) the same kind of foot clenched into a grasping fist of talons. ${NOFX} ${SUFFIX}` },
  zz_debris: { boss: 'b_ziz', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${ZZ} About ten separate torn-off pieces of the storm bird from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: ragged storm-grey feather clumps, broken ivory bone shards, a broken beak tip, a snapped rib, chunks of dark red flesh with feathers, a broken black talon. ${NOFX} ${SUFFIX}` },

  // ── v2 재생성 (첫 묶음 검수 뒤) ──
  zz_eyes2: { boss: 'b_ziz', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${ZZ} Three separate flat objects in one row with wide empty space between them, no piece touches another, all the same size and the same horizontal almond shape, seen straight from the front: 1) a wide open slit-pupil demon eye sunk into a flat patch of wrinkled grey-black skin and tiny dark feathers, thick puffy eyelids around it, only the almond-shaped front of the eye visible, glowing pale yellow iris with a vertical black slit pupil, bloodshot corners; 2) the same flat patch of skin with the eyelids closed and sewn shut with crude black stitches; 3) the same flat patch of skin with a burst empty eye socket, shredded eyelids and dark red blood. NOT a round eyeball, NOT a sphere. ${NOFX} ${NOHALO} ${SUFFIX}` },
  zz_debris2: { boss: 'b_ziz', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${ZZ} About ten separate torn-off pieces of the storm bird from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: ragged dark storm-grey feather clumps, broken ivory bone shards, a broken hooked beak tip, a snapped rib, chunks of dark red flesh with feathers stuck to them, a broken black talon. ${NOFX} ${NOHALO} ${SUFFIX}` },

  // ───────── 마라 (악몽을 낳는 자) — 图片1 = portraits/b_mara ─────────
  mr_head: { boss: 'b_mara', aspect: '1:1', count: 2, refs: ['portrait'], prompt: `${MR} The head of the nightmare hag from 图片1 alone, three-quarter side view facing right: a cracked white porcelain doll-mask face with NO eyes (only faint painted closed eyelids in shallow hollows), faded pink doll cheeks, a vertical slit mouth sewn shut with crude black stitches, hairline cracks and grime on the porcelain, the mask fused onto a gaunt grey-mauve skull at the back with a few black thread-like hair roots, a thin sinewy neck cut flat at the bottom. ${NOFX} ${SUFFIX}` },
  mr_head2: { boss: 'b_mara', aspect: '1:1', count: 1, refs: ['portrait', 'kept'], prompt: `${MR} The same porcelain doll head as 图片2, same three-quarter view facing right, same shape and size, but broken: the upper right part of the forehead porcelain has shattered and fallen away, revealing a pitch-black hollow inside the head with one glowing violet eye staring out of the darkness, jagged broken porcelain edges, fresh cracks spreading over the whole face, a trickle of dark blood from the stitched mouth. ${NOFX} ${SUFFIX}` },
  mr_torso: { boss: 'b_mara', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${MR} Strict side view facing right of the emaciated hunched torso of the hag from 图片1 WITHOUT head, WITHOUT arms and WITHOUT legs: grey-mauve skin stretched tight over protruding ribs and a knobbly bent spine, sunken belly with a crude stitched scar, a torn filthy dark-purple nightgown rag clinging to the back and hanging down in tatters, a thin sinewy neck stump at the upper right, the pelvis at the bottom cut flat. ${NOFX} ${SUFFIX}` },
  mr_arms: { boss: 'b_mara', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${MR} Four separate body pieces of the hag from 图片1 laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a long gaunt grey-mauve upper arm lying horizontal with a sharp pointed elbow bone at the right end, 2) a long thin bony forearm lying horizontal, 3) a long-fingered clawed hand with four spidery fingers spread open and long needle-like yellowed nails, pointing right, 4) the same kind of hand with the long fingers curled into a grasping claw. ${NOFX} ${SUFFIX}` },
  mr_legs: { boss: 'b_mara', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MR} Three separate leg pieces of the hag from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) a thin bony grey-mauve thigh lying horizontal, 2) a thin shin lying horizontal with a big protruding knobbly knee bone at the left end, 3) a long bare bony foot seen from the side with long gripping curled toes and yellowed claws. ${NOFX} ${SUFFIX}` },
  mr_cradle: { boss: 'b_mara', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${MR} Strict side view of the giant ornate wrought-iron baby cradle from 图片1 alone, empty: an oval basket of thin vertical rusted black iron bars with a thick curved top rail and a curled scroll finial at each end, two big curved rocker runners underneath joined by short legs, a torn stained grey mattress visible between the bars, dried blood stains and rust, clear gaps between all bars showing the background. Nobody sits on it. ${NOFX} ${SUFFIX}` },
  mr_flesh: { boss: 'b_mara', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MR} A single wide bloated oval mass of swollen pale violet-red flesh like a giant pulsing tumour, seen from the side, with bulging dark veins, stretched shiny skin, stitched seams, and three pale sleeping porcelain doll faces half pressed and sunk into the flesh, dark blood oozing from the seams. ${NOFX} ${SUFFIX}` },
  mr_faces: { boss: 'b_mara', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${MR} Four separate porcelain baby-doll heads from 图片1 in one row with wide empty space between them, no piece touches another, all seen from the front: 1) a sleeping doll face with closed eyes and faded auburn painted hair, 2) another sleeping doll face tilted slightly with a crack across the cheek, 3) a sleeping doll face with a sad frown and a chipped chin, 4) an awake doll head with wide glassy pale-blue staring eyes, a tiny creepy smile and cracks. ${NOFX} ${SUFFIX}` },
  mr_doll: { boss: 'b_mara', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${MR} Separate ball-jointed porcelain doll parts laid out apart from each other with wide empty space between them, no piece touches another: 1) a very long cracked porcelain doll thigh lying horizontal, 2) a very long porcelain doll shin lying horizontal ending on the right in a pointed doll foot, 3) a round porcelain ball joint, 4) a small porcelain doll arm with a tiny grasping hand, 5) a broken doll neck stump with jagged edges. Yellowed grimy white porcelain with dirt in the cracks. ${NOFX} ${SUFFIX}` },
  mr_hair: { boss: 'b_mara', aspect: '21:9', count: 1, refs: ['portrait'], prompt: `${MR} A single long mass of black thread-like hair lying horizontally across the image, gathered into a tight root knot at the right end and fanning out to the left into many long wavy loose strands as if floating underwater, thin threads, a few strands knotted, faint violet sheen. ${NOFX} ${SUFFIX}` },
  mr_debris: { boss: 'b_mara', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MR} About ten separate broken fragments arranged in a loose grid with wide empty space between pieces, no piece touches another: shards of white porcelain doll faces, a broken porcelain doll hand, bent rusted iron cradle bars, a tangle of black thread, a chipped porcelain eye piece, a torn grey rag. ${NOFX} ${SUFFIX}` },

  // ── v2 재생성 (첫 묶음 검수 뒤) ── 图片2 = 이미 채택한 결과 (Kling 결과 URL 을 그대로 입력)
  mr_head2b: { boss: 'b_mara', aspect: '1:1', count: 2, refs: ['portrait', 'mr_head_2'], prompt: `${MR} The same porcelain doll-mask head as 图片2, the same three-quarter view, the same shape, size, colours and spine neck, but broken: the upper part of the forehead porcelain has shattered and fallen away, revealing a pitch-black hollow inside the head with one glowing violet eye staring out of the darkness, jagged broken porcelain edges, fresh cracks spreading over the whole mask, a trickle of dark blood running from the stitched mouth. ${NOFX} ${SUFFIX}` },
  mr_legs2: { boss: 'b_mara', aspect: '16:9', count: 2, refs: ['portrait', 'mr_torso_1'], prompt: `${MR} Three separate leg pieces of the emaciated hag, with exactly the same grey-mauve skin, painting style and lighting as the torso in 图片2, laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a long thin bony thigh lying horizontal, the hip end on the left, 2) a long thin bony shin lying horizontal with a big knobbly knee cap at the left end and the ankle at the right end, 3) a long bare bony foot seen from the side with long curled gripping toes and cracked yellowed toenails. No cartoon bones, no paws, no gold. ${NOFX} ${SUFFIX}` },
  mr_flesh2: { boss: 'b_mara', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MR} A single wide bloated oval mass of swollen bruised flesh seen from the side, dark wet violet and deep red, covered in bulging purple veins, stretched shiny skin, crude black stitched seams, three pale sleeping porcelain baby-doll faces half sunk and pressed into the flesh, dark blood oozing from the seams, realistic painterly, not pink, not cute, no light beam, no spotlight. ${NOFX} ${SUFFIX}` },

  // ───────── 베헤모스 (부패한 대지의 짐승) — 图片1 = portraits/b_behemoth ─────────
  bh_head: { boss: 'b_behemoth', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${BH} Strict side view (profile) facing right of the head of the rotting boar-hippo beast from 图片1 alone: the front half is a bare cracked boar skull with a huge empty eye socket and long snout bones, the back half is rotting mossy furry hide with a torn pointed ear and small mushrooms growing on it, maggot-ridden torn skin edge between skin and bone, broken blunt upper teeth, a short curved upper tusk, the mouth wide open with the lower jaw clearly separate and dropped open at the hinge, a big upward-curving cracked tusk on the lower jaw, dark empty gap between the jaws, the thick neck cut at the left. ${NOFX} ${SUFFIX}` },
  bh_torso: { boss: 'b_behemoth', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${BH} Strict side view facing right of the huge body of the rotting boar-hippo beast from 图片1 WITHOUT head, WITHOUT legs, WITHOUT trees and WITHOUT the rider: a mountainous barrel-shaped body of mossy bark-like hide with patchy matted fur, rotten holes in the skin, shelf fungi on the flank, a row of short bony spine spikes along the top of the back, a long torn wound across the flank exposing curved ivory ribs and dark red flesh with pale fungal threads, the thick neck stump at the right end, the rump at the left end with a short rat-like tail, hanging moss under the belly, flat leg stumps at the bottom. ${NOFX} ${SUFFIX}` },
  bh_leg: { boss: 'b_behemoth', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${BH} Four separate leg pieces of the rotting beast from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) a huge thick muscular front thigh of mossy hide, vertical, 2) a thick wrinkled elephant-like front shin, vertical, 3) a huge blunt hippo-like foot with four cracked yellowed nails and dried mud, 4) a thick hind leg thigh with patchy fur, vertical. ${NOFX} ${SUFFIX}` },
  bh_trees: { boss: 'b_behemoth', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${BH} Three separate dead twisted trees from the back of the beast in 图片1 standing in one row with wide empty space between them, no tree touches another: gnarled grey-brown bark, bare crooked branches reaching up, hanging grey moss, small pale mushrooms on the trunks, knotholes, each tree ends at the bottom in a flat cut with a few short roots. Different heights: medium, tall, short. ${NOFX} ${SUFFIX}` },
  bh_mush: { boss: 'b_behemoth', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${BH} Four separate objects in one row with wide empty space between them, no piece touches another: 1) a tall giant pale mushroom with a wide domed cream cap with small glowing green spots and a veined stalk, 2) a smaller pale mushroom with a tilted cap, 3) a cluster of five small pale mushrooms on one base, 4) a clump of tiny white flowers and fresh green sprouts. Flat bottoms. ${NOFX} ${SUFFIX}` },
  bh_queen: { boss: 'b_behemoth', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${BH} The pale fungal queen from 图片1 alone, side view facing right: the upper body of a gaunt pale bone-white woman made of fungus and bark, sunken glowing pale-green eyes, long flowing white mycelium hair streaming back to the left, a crown of small mushroom caps, both thin arms hanging down in front with long root-like fingers, her waist dissolving at the bottom into a knot of pale roots and fungus, flat bottom. ${NOFX} ${SUFFIX}` },
  bh_queen2: { boss: 'b_behemoth', aspect: '3:4', count: 1, refs: ['portrait', 'kept'], prompt: `${BH} The same pale fungal queen as 图片2, same side view facing right, same size and same root-knot base, but awake and casting: both thin arms raised high above her head with the long root-like fingers spread like claws, mouth open in a shriek, glowing pale-green eyes wide, hair streaming back. ${NOFX} ${SUFFIX}` },
  bh_sacs: { boss: 'b_behemoth', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${BH} Four separate objects in one row with wide empty space between them, no piece touches another: 1) a swollen translucent fungal spore sac, sickly yellow-green, veined with red, glowing spores visible inside, 2) a similar spore sac slightly smaller and lumpier, 3) a burst spore sac: torn empty membrane flaps with dripping green slime, 4) a round torn wound in mossy hide exposing a pale kneecap bone and dark red raw flesh with dripping blood. ${NOFX} ${SUFFIX}` },
  bh_debris: { boss: 'b_behemoth', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${BH} About ten separate chunks of the rotting beast from 图片1 torn apart, arranged in a loose grid with wide empty space between pieces, no piece touches another: mossy hide chunks with fur, broken bark, bone shards, a broken tusk, rotten dark red flesh with fungus, a broken mushroom cap, a broken branch. ${NOFX} ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || k === id) console.log(`\n# ${k} (${s.boss}, ${s.aspect}, ×${s.count}, refs ${s.refs.join('+')})\n${s.prompt}`);
}
