// Kling prompts for ART-BOSS-1 (painted puppets: 나이트윙 b_nightwing, 밴시 여왕 b_banshee, 둘라한 b_dullahan).
// Model kling-image-v3_0_omni (image_to_image, img_resolution 2k). 图片1 = the boss portrait (assets/portraits/<id>.webp → PNG).
// Templates follow docs/art/BOSS_PIPELINE.md §3: style clause first, one part group per image, flat mid-grey
// background (matte.py keys it), key light from the upper left, no text. Print one prompt:
//   node tools/painted/prompts/art-boss-1.mjs b_nightwing head
// Every call (kept and rejected) is logged in the boss config's "kling" block and in tools/kling/manifest_art-boss-1.json.

export const STYLE = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, rich dark colours, dramatic lighting, highly detailed grotesque horror, no black outlines, not cartoon, not cel-shaded, not 3D render.';
export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels, no numbers.';
const P = (s) => `${STYLE} Subject: a game asset for a 2D cut-out puppet, ${s} ${SUFFIX}`.replace(/\s+/g, ' ').trim();

export const PROMPTS = {
  b_nightwing: {
    head: { aspect: '1:1', n: 2, prompt: P('only the head of the giant vampire bat lord from 图片1, seen from the front turned slightly to the right (three-quarter front view), the mouth gaping extremely wide open in a screech: the upper jaw with two long curved fangs, the separate lower jaw hanging far open below it at the hinge, dark red gums, rows of needle teeth, strings of saliva and blood between the jaws, a black throat. Two huge torn bat ears standing straight up with veined red inner membrane, a crumpled wrinkled leaf-shaped nose, deep-set glowing red eyes, grotesque wrinkled hairless grey skin around the snout, coarse black fur on the skull. Only the head: it ends at the top of the neck with a ragged fur edge, no body, no shoulders.') },
    torso: { aspect: '3:4', n: 2, prompt: P('only the torso of the vampire bat lord from 图片1 seen straight from the front, NO head, NO arms, NO wings, NO legs: a hunched emaciated but muscular grotesque chest and belly, ribs pressing through thin grey-brown hairless skin, pulsing dark veins, old claw scars and stitched wounds, a shaggy black fur mane around the neck stump at the top and on the shoulders, bony knobbed wing-root shoulder joints on both sides, a furry pelvis at the bottom. The neck stump at the top centre, clean edges where the wings and legs attach. The torso is symmetrical and upright.') },
    wing: { aspect: '4:3', n: 2, prompt: P('a single left bat wing of the vampire bat lord from 图片1, spread wide open and seen flat from the front: the shoulder joint at the lower RIGHT corner of the image, a thick sinewy forearm bone going up and to the left to the wrist, a big hooked thumb claw at the wrist, four very long bony fingers fanning out from the wrist to the upper left, left and lower left, a dark leathery membrane stretched between the fingers and down to the shoulder, translucent blood-red where the light passes through, many branching dark veins, several ragged tears and round holes, a scalloped torn trailing edge. The whole wing is inside the image with an empty margin.') },
    wingf: { aspect: '3:4', n: 1, prompt: P('a single left bat wing of the vampire bat lord from 图片1, FOLDED tightly shut like a closed umbrella and hanging down: the shoulder joint at the upper RIGHT, the wrist joint with a big hooked thumb claw at the top left, the long finger bones gathered together pointing straight down, the dark leathery blood-red membrane wrapped in deep folds between them, torn ragged tips at the bottom. The whole folded wing is inside the image with an empty margin.') },
    leg: { aspect: '1:1', n: 2, prompt: P('a single hind leg of the vampire bat lord from 图片1 seen from the side, hanging straight down: a furry muscular thigh at the top, a bony knee with shaggy black fur tufts, a thin sinewy shin, and a big grotesque clawed foot at the bottom with four long hooked black talons spread wide open like a grasping raptor foot. The leg is vertical, thigh top at the top of the image, talons at the bottom, empty margin all around.') },
    debris: { aspect: '16:9', n: 1, prompt: P('12 separate small pieces of the vampire bat lord from 图片1 lying apart in a loose 4 by 3 grid with wide empty space between them, no piece touches another: three torn scraps of blood-red bat wing membrane with ragged edges, a snapped wing finger bone, two clumps of coarse black fur, two long curved fangs, a torn-off pointed bat ear, a broken hooked black talon, a bloody chunk of flesh with a rib, a small clot of dark blood. Each piece fully in frame.') },
  },
  b_banshee: {
    face: { aspect: '1:1', n: 2, prompt: P('only the hooded head of the banshee queen from 图片1 seen from the front, but her face is NOT a skull: a gaunt emaciated ghostly woman\'s face with grey-white skin stretched tight over the bones, hollow dark eye sockets with small glowing teal pupils, black tears running down the cheeks, the mouth unnaturally wide open in a wailing scream with the lower jaw dislocated and hanging far down, long cracked teeth, a black throat. A tattered white hood and veil frames the face, thin pale hair strands. Only the head and hood, it ends at the neck, no shoulders.') },
    skull: { aspect: '1:1', n: 2, prompt: P('only the hooded head of the banshee queen from 图片1 seen from the front, exactly like the portrait: the face is a bare grinning skull with glowing teal eyes in the sockets, but the lower jaw of the skull hangs wide open in a scream showing the black throat and long cracked teeth, cracks across the cranium, a tattered white hood and veil framing the skull. Only the head and hood, it ends at the neck, no shoulders.') },
    body: { aspect: '9:16', n: 2, prompt: P('the body of the banshee queen from 图片1 seen from the front WITHOUT head and WITHOUT arms: a slender ghostly grey-white torso in a tattered translucent white burial gown, a heavy dark iron chain wrapped around the waist and another across the chest, an iron chain necklace with a pendant, the gown flows down and widens into long ragged torn strips that dissolve into wisps of teal ectoplasm mist at the bottom, no feet visible. The shoulders are at the top with clean edges where the arms and neck attach. Symmetrical, upright, whole figure inside the image.') },
    arm: { aspect: '4:3', n: 2, prompt: P('a single arm of the banshee queen from 图片1 stretched out straight horizontally to the right: the shoulder at the left edge, a thin grey-white upper arm, the forearm with a long torn translucent bell-shaped sleeve hanging down below it, a rusted iron manacle with a broken chain link on the wrist, and a skeletal hand with very long clawed bony fingers spread open, palm down, at the right. The arm is straight and level, empty margin all around.') },
    veil: { aspect: '3:4', n: 1, prompt: P('only the long flowing back veil and loose hair of the banshee queen from 图片1 seen from the front, with nothing in front of it (no face, no body): a tall tattered translucent white veil that starts narrow at the top where it covers the back of the head and widens downwards like a cloak, long pale grey-white hair strands spilling over it, torn holes and ragged strips at the bottom, faint teal glow. Whole veil inside the image.') },
    chain: { aspect: '21:9', n: 1, prompt: P('a single straight horizontal chain of 8 heavy old iron links joined end to end, strict side view, perfectly straight and level, running left to right across the whole image with an empty margin at both ends, alternating link orientation (one link seen flat as an oval ring, the next seen edge-on as a thick bar), rusted dark iron with scratches and faint teal ghost glow in the grooves, like the chains of 图片1.') },
    debris: { aspect: '16:9', n: 1, prompt: P('12 separate small pieces of the banshee queen from 图片1 lying apart in a loose 4 by 3 grid with wide empty space between them, no piece touches another: three torn scraps of white translucent veil cloth, two broken rusted chain links, a broken iron manacle, a cracked piece of skull, two long cracked teeth, a finger bone with a long claw, two blobs of glowing teal ectoplasm. Each piece fully in frame.') },
  },
  b_dullahan: {
    horse: { aspect: '16:9', n: 2, prompt: P('strict side view (profile) facing RIGHT of the body of the pale spectral warhorse from 图片1: only the barrel and haunches with the saddle, NO head, NO neck, NO legs, NO tail. The neck is cut off at its base with a clean edge at the upper right, the legs stop at the tops of the thighs with clean edges. A black leather saddle with a dark red saddle cloth with gold trim, girth and breast strap. The horse skin is ghostly pale blue-white and half rotten: large patches where the skin has sloughed off revealing the ribs and dark sinew underneath, stitched wounds, faint blue soul fire glowing between the ribs.') },
    head: { aspect: '4:3', n: 2, prompt: P('strict side view (profile) facing RIGHT of the head and long arched neck of the pale spectral warhorse from 图片1: the base of the neck at the lower left, the head at the upper right pointing right and slightly down, the horse skull half exposed where the skin is torn from the cheek and jaw, bared teeth, a hollow eye socket with a glowing blue eye, a leather bridle with gold studs, a wild flowing mane of white-blue ghost fire along the neck. Clean cut edge at the neck base.') },
    legs: { aspect: '16:9', n: 2, prompt: P('two separate legs of the pale spectral warhorse from 图片1 standing side by side with wide empty space between them, strict side view facing right, each leg perfectly straight and vertical from the top of the thigh down to the hoof: on the left a FORE leg, on the right a HIND leg with its backward-bent hock. Ghostly pale blue-white skin torn at the knees showing bone and sinew, iron-shod black hooves with faint blue flames licking around them. Clean cut edges at the top of each thigh.') },
    torso: { aspect: '3:4', n: 2, prompt: P('strict side view (profile) facing RIGHT of the armoured torso of the headless black knight from 图片1, with NO head, NO helmet, NO arms, NO legs, NO cape: the neck is an empty charred stump inside a jagged spiked iron gorget collar, blackened iron breastplate with gold filigree and dents, a huge spiked pauldron on the near shoulder, a skirt of overlapping fauld plates and tassets at the waist, clean edges where the arms and legs attach.') },
    leg: { aspect: '3:4', n: 2, prompt: P('a single armoured leg of the black knight from 图片1, strict side view facing right, perfectly straight and vertical: a plated cuisse thigh at the top, a spiked poleyn knee, a greave, and a pointed black iron sabaton foot pointing to the right with a spur at the heel. Clean cut edge at the top of the thigh, empty margin all around.') },
    arms: { aspect: '16:9', n: 2, prompt: P('two separate armoured arms of the black knight from 图片1 lying apart with wide empty space between them, strict side view: on the left an arm reaching forward to the right, straight and level, with a spiked couter at the elbow and the black gauntlet clenched into a fist; on the right an arm reaching up with the gauntlet hand open palm up, clawed fingers curled as if holding a ball. Each arm starts with a clean edge at the shoulder.') },
    lance: { aspect: '21:9', n: 1, prompt: P('a single long cruel war lance of the black knight from 图片1, perfectly straight and horizontal across the whole image, pointing RIGHT, with an empty margin at both ends: a long dark iron-banded wooden shaft, a flared conical black iron vamplate hand guard at the left third, and a long serrated spearhead with barbed side hooks at the right end, faint blue runes glowing on the blade.') },
    skull: { aspect: '1:1', n: 1, prompt: P('a single human skull, the severed head of the headless knight from 图片1, seen from the side facing right, cracked and charred black around the edges, some teeth missing, the eye sockets and cracks glowing bright orange from fire inside, no flames outside the skull, no body.') },
    cape: { aspect: '3:4', n: 1, prompt: P('a single tattered dark crimson knight\'s cape from 图片1 hanging straight down from a straight horizontal top edge, seen from the side, heavy wool with a black lining visible at the edges, long ragged torn strips and holes at the bottom, burnt edges. Whole cape inside the image.') },
    debris: { aspect: '16:9', n: 1, prompt: P('12 separate small pieces of the headless black knight and his spectral horse from 图片1 lying apart in a loose 4 by 3 grid with wide empty space between them, no piece touches another: three broken blackened armour plate shards, a snapped iron spike, a bent gold-trimmed rivet plate, a charred skull fragment with an eye socket, a jaw bone with teeth, a horse rib, a horseshoe with nails, two chunks of pale ghostly horse flesh with glowing blue veins. Each piece fully in frame.') },
  },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const [id, shot] = process.argv.slice(2);
  const s = PROMPTS[id]?.[shot];
  console.log(s ? JSON.stringify(s, null, 1) : Object.fromEntries(Object.entries(PROMPTS).map(([k, v]) => [k, Object.keys(v)])));
}
