// ART-BOSS-6 Kling 프롬프트 (2부 보스: 나르키사 b_narkissa · 몰록 b_moloch · 다곤 b_dagon)
// 모델 kling-image-v3_0_omni · image_to_image · img_resolution 2k. 图片1 = 보스 초상화 (assets/portraits/<id>.webp → PNG 업로드).
//   나르키사 1형태 = portraits/b_narkissa, 깨진 여제(3페이즈) = portraits/b_narkissa2, 몰록 = portraits/b_moloch, 다곤 = portraits/b_dagon.
// 템플릿: docs/art/BOSS_PIPELINE.md §3 (스타일 문구를 맨 앞에, 평평한 중간 회색 배경 + 왼쪽 위 키라이트 공통 꼬리말).
// 나르키사·몰록은 정면(대칭) 퍼핏 — 벡터 그림도 정면에서 좌우 반전만 한다. 다곤은 옆모습(오른쪽을 봄) 퍼핏.
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_art-boss-6.json 과 configs/<id>.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/art-boss-6.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';

const NK = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, glossy black obsidian glass with cold silver-white rim highlights, pale cracked porcelain, iridescent mirror glass with faint rainbow sheen, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const MO = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, tarnished hammered bronze with green verdigris, soot and rivets, blackened iron, glowing molten orange heat in the cracks, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const DG = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, slimy wet grey-green fish flesh with barnacles and warts, rotten dark teal priest robes with tarnished gold trim, pale bioluminescent cyan glow, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const NOFX = 'No smoke, no mist, no fire, no sparks, no particles, no glow haze, no magic effects around the object.';

/** shot → { boss, aspect, count, refs (image_1 = 초상화, 그 뒤 = 이미 채택한 결과), prompt } */
export const SHOTS = {
  // ───────── 나르키사 (만경의 여제) — 图片1 = portraits/b_narkissa ─────────
  nk_head: { boss: 'b_narkissa', aspect: '1:1', count: 2, refs: ['portrait'], prompt: `${NK} The head and long slender neck of the glass empress from 图片1 alone, seen straight from the front: an elegant expressionless porcelain mask face split vertically down the middle, the left half glossy black glass studded with many small mismatched staring eyes of different sizes, the right half smooth white cracked porcelain with one cold pale eye, fine hairline cracks spreading over the mask, a thin closed mouth, a slender black glass neck ending in a clean flat cut at the bottom. NO crown, NO halo, NO needles and NO spikes around the head. ${NOFX} ${SUFFIX}` },
  nk_head2: { boss: 'b_narkissa', aspect: '1:1', count: 2, refs: ['portrait2'], prompt: `${NK} The monstrous head of the broken glass empress from 图片1 alone, seen straight from the front: the mask shattered away into a hollow face of black glass and white porcelain crowded with dozens of glowing pale staring eyes of different sizes, the mouth torn impossibly wide open into a huge vertical maw lined with long jagged mirror-glass fangs on the upper and the lower jaw, the lower jaw hanging clearly separated below the upper head with a wide pitch-black gap (dark empty throat) between the teeth, the neck cut flat at the bottom. NO halo, NO flying shards, NO disc behind the head. ${NOFX} ${SUFFIX}` },
  nk_crown: { boss: 'b_narkissa', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${NK} A single crown-halo of the glass empress from 图片1 alone, seen straight from the front: about eleven long thin needle-like spikes of iridescent glass and sharp mirror slivers radiating outward in a wide upward half circle (a fan) from a small dark central hub at the bottom middle, the longest needle in the centre pointing straight up, the side needles getting shorter towards the left and right, small glass shards between the needles. No head, no face. ${NOFX} ${SUFFIX}` },
  nk_halo2: { boss: 'b_narkissa', aspect: '1:1', count: 1, refs: ['portrait2'], prompt: `${NK} A single large round halo disc from behind the head of 图片1 alone, seen straight from the front: a circular shattered mirror made of many broken reflective glass pieces arranged radially around an empty dark round hole in the centre, black cracks between the pieces, jagged broken outer edge with a few long glass spikes sticking outward, cold pale silver-blue reflections. No head, no face. ${NOFX} ${SUFFIX}` },
  nk_torso: { boss: 'b_narkissa', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${NK} The upper body of the glass empress from 图片1 WITHOUT head and WITHOUT arms, seen straight from the front: a slender feminine torso of glossy sculpted black obsidian glass like an armoured bodice, sharp spiked glass pauldrons with clusters of long shards on both shoulders, round empty joint sockets where the arms would attach, a glowing green gem set in the centre of the chest, a very narrow waist cut cleanly and flat at the bottom, the neck stump cut cleanly and flat at the top. ${NOFX} ${SUFFIX}` },
  nk_gown: { boss: 'b_narkissa', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${NK} The long gown of the glass empress from 图片1 alone without any body, legs or arms, seen straight from the front: a tall bell-shaped skirt made of many long pointed vertical mirror shards joined edge to edge by black glass lead lines, each mirror shard reflecting a different pale screaming human face with a wide open mouth and white glowing eyes, very narrow at the top (the waist, cut flat) and very wide at the bottom, the hem made of jagged downward-pointing shard tips. ${NOFX} ${SUFFIX}` },
  nk_shards: { boss: 'b_narkissa', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${NK} Seven separate long narrow pointed mirror-glass shards from the gown of 图片1 laid out standing upright in one row with wide empty space between them, no shard touches another, each shard pointing down at the bottom, framed by a thin black glass edge, and each reflecting one pale screaming human face with a wide open mouth and white glowing eyes, iridescent rainbow sheen on the glass. ${NOFX} ${SUFFIX}` },
  nk_limbs: { boss: 'b_narkissa', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${NK} Five separate body pieces of the glass empress from 图片1 laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a slender upper arm of glossy black glass lying horizontal with a round spiral joint cap at the left end, 2) a thinner forearm of glossy black glass lying horizontal, 3) a long thin clawed hand of black glass seen from the back, pointing right, five long thin fingers spread open ending in sharp silver talons, 4) a long curved blade made of one sharp iridescent mirror shard, pointing right, 5) a small ornate hand mirror with a thorny silver frame and handle. ${NOFX} ${SUFFIX}` },
  nk_legs: { boss: 'b_narkissa', aspect: '21:9', count: 1, refs: ['portrait'], prompt: `${NK} Two separate pieces of one giant spider leg of the glass empress from 图片1, made of glossy black obsidian glass with cold silver highlights, strict side view, each piece lying perfectly straight and horizontal with wide empty space between them: 1) at the top, a long thick upper leg segment with a large round disc-shaped joint cap with a spiral groove at each end, 2) at the bottom, a long lower leg segment starting with a round joint cap on the left and tapering to a long sharp pale silver claw point on the right. ${NOFX} ${SUFFIX}` },
  nk_mirror: { boss: 'b_narkissa', aspect: '3:4', count: 1, refs: ['portrait'], prompt: `${NK} A single ornate oval wall mirror from the throne hall of 图片1, seen straight from the front: a tall oval frame of black obsidian glass and tarnished silver with thorny spikes and small sharp glass shards around the rim, the mirror glass inside plain pale grey-blue and empty (no reflection, no figure), a faint diagonal glare. ${NOFX} ${SUFFIX}` },
  nk_debris: { boss: 'b_narkissa', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${NK} About ten separate broken fragments of the glass empress from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: sharp shards of glossy black obsidian glass of different sizes, broken pieces of white porcelain mask with a staring eye, iridescent mirror shards, a snapped glass needle, a broken spiral joint cap. ${NOFX} ${SUFFIX}` },

  // ───────── 몰록 (용광로의 우상) — 图片1 = portraits/b_moloch ─────────
  mo_torso: { boss: 'b_moloch', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${MO} The massive torso of the bronze bull idol from 图片1 WITHOUT head, WITHOUT arms, WITHOUT legs and WITHOUT chains, seen straight from the front: huge hunched muscular shoulders with rows of small bone spikes, a barrel chest of tarnished hammered bronze with verdigris, rivet seams and cracks glowing faintly orange, a large round furnace opening in the middle of the belly framed by a thick riveted iron ring, the inside of the opening completely empty and flat black, round shoulder sockets, the neck stump cut flat at the top, cut flat at the hips at the bottom. ${NOFX} ${SUFFIX}` },
  mo_head: { boss: 'b_moloch', aspect: '1:1', count: 2, refs: ['portrait'], prompt: `${MO} The head of the bronze bull idol from 图片1 alone, seen straight from the front, WITHOUT horns (only two short round horn sockets on the top of the skull): a snarling metal bull face with deep brow ridges, two glowing orange eyes, flaring nostrils with a heavy iron nose ring, the mouth slightly open with a molten orange glow inside, coarse bristly fur along the jaw and cheeks, the neck cut flat at the bottom. ${NOFX} ${SUFFIX}` },
  mo_horns: { boss: 'b_moloch', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MO} Three separate pieces laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a single huge curved bull horn of ridged ivory and bronze, the thick round root at the lower left and the sharp tip curving up to the upper right, 2) a short thick broken horn stump with a jagged broken top that glows molten orange inside, 3) the broken-off tip of the horn. ${NOFX} ${SUFFIX}` },
  mo_arms: { boss: 'b_moloch', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${MO} Four separate body pieces of the bronze bull idol from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) a huge muscular bronze upper arm lying horizontal with a round shoulder ball at the left end, 2) a muscular bronze forearm lying horizontal with a spiked black iron bracer around it, 3) a huge clenched bronze fist seen from the side, holding nothing, with a round hole through the grip, 4) a massive bronze thigh and knee pointing down. ${NOFX} ${SUFFIX}` },
  mo_hammer: { boss: 'b_moloch', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MO} A single giant forge hammer of the bronze idol from 图片1 lying perfectly horizontal: a long dark wooden handle wrapped with iron bands on the left, a massive square black iron hammer head on the right with engraved runes and rivets, the striking faces scorched and glowing faintly orange. ${NOFX} ${SUFFIX}` },
  mo_tongs: { boss: 'b_moloch', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MO} A single half of a pair of giant blacksmith tongs from 图片1 lying horizontal: one long straight black iron arm with a riveted pivot ring near the middle and a hooked curved claw jaw at the right end glowing red-hot orange, dripping molten metal. Only one arm of the tongs. ${NOFX} ${SUFFIX}` },
  mo_chimney: { boss: 'b_moloch', aspect: '9:16', count: 1, refs: ['portrait'], prompt: `${MO} A single tall iron furnace chimney stack from the back of the idol in 图片1, standing upright: a tall cylinder of sooty riveted black iron and bronze bands, slightly wider at the top rim, the open top blackened, the bottom end cut flat. No smoke and no fire coming out. ${SUFFIX}` },
  mo_souls: { boss: 'b_moloch', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MO} Three separate tormented faces of souls trapped in the furnace of 图片1, laid out in one row with wide empty space between them, no face touches another: each a gaunt skull-like human face of pale ash-grey charred skin with hollow glowing orange eye sockets and a screaming wide open mouth, one with hands pressed against its cheeks. ${NOFX} ${SUFFIX}` },
  mo_apron: { boss: 'b_moloch', aspect: '3:4', count: 1, refs: ['portrait'], prompt: `${MO} A single heavy torn leather blacksmith apron (loincloth) of the idol from 图片1 hanging straight down, seen from the front: dark scorched brown leather with burn holes, a riveted iron belt edge at the top (cut flat), long ragged tattered strips at the bottom hem. ${NOFX} ${SUFFIX}` },
  mo_grate: { boss: 'b_moloch', aspect: '1:1', count: 1, refs: ['portrait'], prompt: `${MO} A single round furnace grate door of the idol from 图片1 seen straight from the front: six thick vertical black iron bars inside a heavy riveted round iron frame, soot-blackened bars with red-hot orange edges, the gaps between the bars completely empty showing the plain grey background. ${NOFX} ${SUFFIX}` },
  mo_chain: { boss: 'b_moloch', aspect: '21:9', count: 1, refs: ['portrait'], prompt: `${MO} A single heavy iron chain from 图片1 lying perfectly straight and level across the whole image width with empty margin at both ends, strict side view: about ten big oval rusted black iron links joined end to end, alternating links seen from the side and from the front, clear gaps inside every link, a big curved iron hook at the right end. ${NOFX} ${SUFFIX}` },
  mo_debris: { boss: 'b_moloch', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${MO} About ten separate broken pieces of the bronze idol from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: jagged torn plates of hammered bronze with glowing orange broken edges, big iron rivets, a broken chain link, chunks of black iron grate, cooling lumps of slag with molten orange cracks. ${NOFX} ${SUFFIX}` },

  // ───────── 다곤 (가라앉은 성소의 사제왕) — 图片1 = portraits/b_dagon (옆모습, 오른쪽을 봄) ─────────
  dg_head: { boss: 'b_dagon', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${DG} The huge anglerfish head of the priest-king from 图片1 alone in strict side view (profile) facing right: a bulging cloudy white eye, barnacles and warts on the skull, a crest of thin spiny dorsal fin rays along the top of the head, gill folds behind the jaw, the mouth gaping wide open showing long crooked needle teeth and a dark red throat, the lower jaw clearly separate and dropped open at the hinge with a dark gap behind it, fleshy whisker barbels hanging from the chin, the neck cut at the bottom left. NO crown, NO lures, NO glowing bulbs. ${NOFX} ${SUFFIX}` },
  dg_torso: { boss: 'b_dagon', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${DG} The hunched bloated body of the fish priest-king from 图片1 WITHOUT head and WITHOUT arms, strict side view facing right: a massive barnacle-crusted grey-green fish-flesh torso with a slimy sheen and a sagging pale belly, three red gill slits across the ribs, a rotten dark teal priest robe with tarnished gold embroidered trim hanging open over the back and falling down in tattered folds, a red pleated vestment over the chest, the neck stump at the top right, the robe hem ragged at the bottom. ${NOFX} ${SUFFIX}` },
  dg_crown: { boss: 'b_dagon', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${DG} Three separate pieces laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a small low crown of rusted gold seen from the side with branching red coral growing up from it and small pearls, 2) a single long thin fleshy anglerfish lure stalk curving up and to the right, 3) a single round anglerfish lure bulb, translucent pale cyan flesh glowing from inside. ${NOFX} ${SUFFIX}` },
  dg_arm: { boss: 'b_dagon', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${DG} Four separate body pieces of the fish priest-king from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) a thick barnacled grey-green upper arm lying horizontal with a ragged dark teal robe sleeve at the shoulder end on the left, 2) a slimy grey-green forearm lying horizontal, 3) a webbed fish hand clenched in a fist holding nothing, with a round hole through the grip, 4) a webbed fish hand spread open with long hooked black talons, pointing right. ${NOFX} ${SUFFIX}` },
  dg_crozier: { boss: 'b_dagon', aspect: '21:9', count: 1, refs: ['portrait'], prompt: `${DG} A single tall coral crozier staff of the priest-king from 图片1 lying perfectly horizontal across the whole image width with empty margin at both ends: a long straight staff of dark red coral and wood on the left, ending on the right in a large curled spiral hook (crook) of spiky red coral with small branches and a pale glowing pearl set in the curl. ${NOFX} ${SUFFIX}` },
  dg_tentacle: { boss: 'b_dagon', aspect: '21:9', count: 2, refs: ['portrait'], prompt: `${DG} A single long eel-like tentacle of the priest-king from 图片1 lying perfectly straight and level across the whole image width with empty margin at both ends, strict side view: thick at the root on the left and tapering to a thin curled tip on the right, dark slate grey-green slimy skin on top with barnacles, a row of pale pink round suckers along the underside, clear segment wrinkles. ${NOFX} ${SUFFIX}` },
  dg_organ: { boss: 'b_dagon', aspect: '3:4', count: 1, refs: ['portrait'], prompt: `${DG} A cluster of seven tall corroded church organ pipes of different heights fused together side by side, seen from the side, green verdigris metal with tarnished gold bands, barnacles and fish flesh growing over their roots, dark open sound-mouths near the bottom of each pipe, the tallest pipes in the middle, the bottom edge ragged flesh. ${NOFX} ${SUFFIX}` },
  dg_pilgrims: { boss: 'b_dagon', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${DG} Three separate drowned pilgrims embedded in round pearly nacre cysts, laid out in one row with wide empty space between them, no piece touches another: each a pale bloated drowned human head and shoulders half sunk into a round shell of iridescent mother-of-pearl, eyes rolled white, mouth open in a silent moan, one reaching out with a pale hand. ${NOFX} ${SUFFIX}` },
  dg_debris: { boss: 'b_dagon', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${DG} About ten separate chunks of the fish priest-king from 图片1 torn apart, arranged in a loose grid with wide empty space between pieces, no piece touches another: slimy grey-green flesh chunks with barnacles, torn fin membranes, broken needle teeth, broken pieces of red coral, a cracked pearl, a broken verdigris organ pipe. ${NOFX} ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || k === id) console.log(`\n# ${k} (${s.boss}, ${s.aspect}, ×${s.count}, refs ${s.refs.join('+')})\n${s.prompt}`);
}
