// ART-BOSS-5 Kling 프롬프트 (드라큘라 백작 b_dracula 두 형태 · 혼돈의 군주 b_chaos)
// 모델 kling-image-v3_0_omni · image_to_image · img_resolution 2k. 图片1 = 보스 초상화 (assets/portraits/<id>.webp → PNG 업로드).
//   드라큘라 1형태 = portraits/b_dracula, 2형태(마왕) = portraits/b_dracula2, 혼돈의 군주 = portraits/b_chaos.
// 템플릿: docs/art/BOSS_PIPELINE.md §3 (스타일 문구를 맨 앞에, 평평한 중간 회색 배경 + 왼쪽 위 키라이트 공통 꼬리말).
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_art-boss-5.json 과 configs/<id>.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/art-boss-5.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';

const DR = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, deathly pale grey-violet skin, black velvet and deep blood-red silk, tarnished gold, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const DM = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, blood-red scaled demon hide with dark crimson shadows, dark ridged horn and old bone, glowing yellow eyes, warm orange rim light, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const CH = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, black obsidian crystal and void-dark cosmic flesh speckled with tiny glowing violet star lights, violet and magenta glow, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const NOFX = 'No smoke, no mist, no fire, no sparks, no particles, no magic effects around the object.';

/** shot → { boss, aspect, count, refs (image_1 = 초상화, 그 뒤 = 이미 채택한 결과), prompt } */
export const SHOTS = {
  // ───────── 드라큘라 1형태 (귀족) — 图片1 = portraits/b_dracula ─────────
  dr_head_a: { boss: 'b_dracula', aspect: '1:1', count: 2, refs: ['portrait'], prompt: `${DR} The head of the vampire count from 图片1 alone, in strict side view (profile) facing right. Gaunt aristocratic face with deathly pale grey skin, sharp high cheekbones, hollow cheeks, a long hooked nose, a long pointed ear, glowing blood-red eyes under a sharp black brow, black hair slicked straight back from a sharp widow's peak and falling behind the head to the nape, a thin cruel smile with the tip of one long white fang showing over the lower lip. The neck is cut cleanly and straight at its base. No collar, no shoulders, no body, no hands. ${NOFX} ${SUFFIX}` },
  dr_head_b: { boss: 'b_dracula', aspect: '1:1', count: 1, refs: ['portrait', 'dr_head_a'], prompt: `${DR} The same head as 图片2 (same hair, face, ear, skin and colours), strict side view (profile) facing right, but now in monstrous rage: the mouth torn unnaturally wide open in a hissing snarl showing two very long sharp vampire fangs and rows of small pointed teeth, the lips pulled far back, the lower jaw dropped, the eyes blazing bright red, dark veins bulging on the temple and the cheek. The neck is cut cleanly and straight at its base. No collar, no shoulders, no body. ${NOFX} ${SUFFIX}` },
  dr_torso: { boss: 'b_dracula', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${DR} The upper body (torso only) of the vampire count from 图片1, strict side view facing right: a slim black velvet tailcoat with a very high stiff standing collar lined in blood red rising behind the neck, a dark red brocade waistcoat with small gold buttons, a black silk cravat with a ruby brooch at the throat, narrow proud shoulders, the neck cut cleanly at the top, the coat cut straight across at the hips at the bottom. No arms (the shoulders end in rounded sleeve stumps), no head, no cape, no legs. ${NOFX} ${SUFFIX}` },
  dr_limbs: { boss: 'b_dracula', aspect: '4:3', count: 1, refs: ['portrait'], prompt: `${DR} Four separate body pieces of the vampire count from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) at the top left, an upper arm in a black velvet coat sleeve from shoulder to elbow, lying horizontal, 2) at the top right, a forearm in a black velvet sleeve with a white lace cuff and a long thin deathly pale hand, the long bony fingers ending in sharp claws and spread wide open, lying horizontal and pointing right, 3) at the bottom left, another forearm in a black sleeve with a lace cuff and a pale clawed hand curled into a grasping claw, lying horizontal and pointing right, 4) at the bottom right, one long thin leg in black trousers with a pointed black leather boot, standing straight up, side view, toe pointing right. ${NOFX} ${SUFFIX}` },
  dr_cape: { boss: 'b_dracula', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${DR} A single half of the vampire count's huge cape from 图片1, spread wide open like a bat wing and seen flat from the side: gathered at one point at the top left corner (the shoulder), the cloth fanning out to the right and downward, a thin black velvet outer edge and a glossy blood-red silk lining filling most of the surface, the long lower hem cut into sharp scalloped bat-wing points, soft folds radiating from the gathered corner. Only the cape, no person, no arm. ${NOFX} ${SUFFIX}` },
  dr_cloak: { boss: 'b_dracula', aspect: '3:4', count: 1, refs: ['portrait'], prompt: `${DR} The black cape of the vampire count from 图片1 wrapped tightly closed around an invisible body, seen from the side: a tall narrow column of heavy black velvet from a very high blood-red standing collar at the top down to the ankles, the front edge held closed, heavy vertical folds with dim violet highlights, a thin line of red silk lining along the front edge, the top is an empty hollow collar opening (no head), the bottom hem flat. Only the cloak, no person visible. ${NOFX} ${SUFFIX}` },
  dr_bats: { boss: 'b_dracula', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${DR} Five separate black vampire bats laid out in one row with wide empty space between them, no bat touches another, each flying and seen from the side facing right: 1) wings raised high, 2) wings level and fully spread, 3) wings swept down, 4) wings half folded, 5) one bat seen from the front with wings spread wide. Leathery black wings with dark red veins, tiny glowing red eyes, small white fangs. ${NOFX} ${SUFFIX}` },
  dr_morph: { boss: 'b_dracula', aspect: '3:4', count: 2, refs: ['portrait', 'portrait2'], prompt: `${DR} The vampire count from 图片1 in the middle of a horrifying transformation into the huge red demon of 图片2, strict side view facing right, the whole body from head to feet, hunched and writhing: his black tailcoat and pale skin splitting and tearing open, bulging blood-red scaled demon muscle bursting out through the rips, the spine arching with bony spikes pushing through the back, two dark curved horns tearing out of the forehead, the jaw stretching into a fanged muzzle, the clawed hands elongating, torn tatters of the red-lined cape hanging from the shoulders, glowing yellow-red eyes. Grotesque body horror. ${NOFX} ${SUFFIX}` },

  // ───────── 드라큘라 2형태 (진·드라큘라, 날개 달린 마왕) — 图片1 = portraits/b_dracula2 ─────────
  dm_head: { boss: 'b_dracula', aspect: '4:3', count: 2, refs: ['portrait2'], prompt: `${DM} The horned head of the red demon from 图片1 alone, strict side view (profile) facing right, the mouth wide open in a roar showing both rows of long sharp fangs and a dark red throat, the lower jaw clearly separate and dropped open at the hinge with a dark gap behind it, two huge dark ridged horns curving back and then up from the skull, a long pointed bat ear, a spiky black mane along the back of the head, glowing yellow eyes under a heavy scaled brow, blood-red scaled skin. The neck is cut cleanly at its base. No body. ${NOFX} ${SUFFIX}` },
  dm_torso: { boss: 'b_dracula', aspect: '3:4', count: 2, refs: ['portrait2'], prompt: `${DM} The upper body of the red demon from 图片1 alone, strict side view facing right: an enormous hunched muscular chest and back covered in blood-red scales, rows of dark bony spikes along the spine and on top of the shoulders, the thick neck stump cut cleanly at the top front, a glowing orange hellfire rune burning in the centre of the chest, the belly muscles, a black ragged loincloth at the waist, cut straight across at the hips at the bottom. No head, no arms (the shoulders end in rounded stumps), no wings, no legs. ${NOFX} ${SUFFIX}` },
  dm_arm: { boss: 'b_dracula', aspect: '4:3', count: 1, refs: ['portrait2'], prompt: `${DM} Three separate pieces of the arm of the red demon from 图片1 laid out apart from each other in three horizontal rows with wide empty space between them, each piece lying straight and horizontal, pointing right: 1) a huge muscular scaled upper arm from shoulder to elbow with bone spikes on the back of the elbow, 2) a massive scaled forearm with its hand attached, the long fingers ending in huge black hooked talons and spread wide open, palm down, 3) another forearm with its hand clenched into a claw with the black talons curled in. Blood-red scales, dark spikes. ${NOFX} ${SUFFIX}` },
  dm_leg: { boss: 'b_dracula', aspect: '4:3', count: 1, refs: ['portrait2'], prompt: `${DM} Three separate pieces of the leg of the red demon from 图片1 laid out apart from each other with wide empty space between them, no piece touches another: 1) at the top, a thick muscular scaled thigh lying horizontal, 2) in the middle, a long digitigrade lower leg (shin and hock like a beast) lying horizontal, 3) at the bottom, a huge clawed demon foot with three long black talons standing flat on its sole, toes pointing right, side view. Blood-red scales, dark spikes. ${NOFX} ${SUFFIX}` },
  dm_wing: { boss: 'b_dracula', aspect: '4:3', count: 2, refs: ['portrait2'], prompt: `${DM} A single huge demonic bat wing of the red demon from 图片1 spread wide: a thick scaled arm bone rising from the root at the lower left to a curved black hook claw at the wrist at the top, long finger bones fanning out to the right, a translucent blood-red leathery membrane with dark veins stretched between the fingers, the lower edge ragged and scalloped with a few small tears, lit from behind by a warm glow. Only the wing. ${NOFX} ${SUFFIX}` },
  dm_tail: { boss: 'b_dracula', aspect: '21:9', count: 1, refs: ['portrait2'], prompt: `${DM} The long tail of the red demon from 图片1 alone: a single straight horizontal tail lying perfectly straight and level across the whole image width with empty margin at both ends, thick at the root on the left, tapering to the right and ending in a sharp arrowhead-shaped spade tip, blood-red scales on top, a paler ridged belly underneath, a row of small dark spikes along the top edge. ${NOFX} ${SUFFIX}` },
  dm_debris: { boss: 'b_dracula', aspect: '16:9', count: 1, refs: ['portrait2'], prompt: `${DM} About nine separate chunks of the red demon from 图片1 torn apart, arranged in a loose grid with wide empty space between pieces, no piece touches another: scaled blood-red flesh chunks with dark red undersides, a broken dark horn tip, snapped black talons, torn pieces of red leathery wing membrane, a cracked bone spike, a lump of hide with glowing orange ember cracks. ${NOFX} ${SUFFIX}` },

  // ───────── 혼돈의 군주 — 图片1 = portraits/b_chaos ─────────
  ch_head: { boss: 'b_chaos', aspect: '1:1', count: 2, refs: ['portrait'], prompt: `${CH} The head of the cosmic demon lord from 图片1 alone, seen straight from the front: an angular skull-like face of black obsidian crystal, a tall broken crown of long jagged black crystal spikes rising from the top of the head, deep eye sockets with two glowing violet eyes, a closed vertical third-eye slit in the middle of the forehead, the mouth wide open showing two rows of long pale fangs and a glowing magenta throat, the lower jaw clearly separate and dropped open below the face with a dark gap. Only the head, no neck, no body, no shoulders. ${NOFX} ${SUFFIX}` },
  ch_body: { boss: 'b_chaos', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `${CH} The body of the cosmic demon lord from 图片1 without its head, seen straight from the front: huge hunched shoulders bristling with long black crystal spikes, a massive chest of dark void flesh and black obsidian plates speckled with dozens of tiny glowing violet star-lights and small glowing eyes, the lower body narrowing downward into a mass of thick dark writhing tentacles and spikes that end in points at the bottom. A flat empty neck socket at the top centre. No arms, no head. ${NOFX} ${SUFFIX}` },
  ch_arm: { boss: 'b_chaos', aspect: '4:3', count: 1, refs: ['portrait'], prompt: `${CH} A single long monstrous arm of the cosmic demon lord from 图片1 lying horizontal and pointing right: a gnarled arm of black obsidian and void flesh from the spiked shoulder joint on the left to an enormous clawed hand on the right with five long black crystal talons spread open, long crystal spikes growing from the elbow and the forearm, a few tiny glowing violet eyes along the arm. Only the arm. ${NOFX} ${SUFFIX}` },
  ch_tentacle: { boss: 'b_chaos', aspect: '21:9', count: 2, refs: ['portrait'], prompt: `${CH} A single long tentacle of the cosmic demon lord from 图片1 lying perfectly straight and level across the whole image width with empty margin at both ends, thick at the root on the left and tapering to a thin sharp tip on the right, dark void flesh with black obsidian ridges and small crystal spikes on top, a row of glowing magenta suckers and tiny violet eyes along the underside. Clear, straight, not curled. ${NOFX} ${SUFFIX}` },
  ch_eyes: { boss: 'b_chaos', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${CH} Four separate pieces for a floating eyeball monster from 图片1, laid out in one row with wide empty space between them, no piece touches another: 1) a large round glossy eyeball seen straight on, white sclera laced with dark violet veins, with NO iris and NO pupil (blank white centre), 2) a separate round glowing magenta iris disk with a thin vertical black slit pupil, 3) a separate curved fleshy dark violet eyelid shaped like a half moon, 4) a round eyeball burst and ruptured, split open and leaking dark violet ichor. ${NOFX} ${SUFFIX}` },
  ch_shards: { boss: 'b_chaos', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${CH} About ten separate floating fragments from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: sharp black obsidian crystal shards of different sizes with faint violet edges, broken spikes of a black crystal crown, and one large faceted glowing violet-magenta crystal heart wrapped in dark veins. ${NOFX} ${SUFFIX}` },
  ch_echoes: { boss: 'b_chaos', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1, soft visible brush strokes, not cartoon. Five separate ghostly shadow apparitions made of dark violet void matter, laid out in one row with wide empty space between them, no piece touches another, each a dark translucent violet-black silhouette with a faint glowing violet rim and glowing eyes: 1) the head and long neck of a huge sea serpent rising straight up with cyan eyes, 2) a giant clockwork fist made of gears with orange light, 3) a tall ice queen in a long gown with a spiked crown and pale icy eyes, 4) a hooded grim reaper holding a scythe with green eyes, 5) a vampire lord wrapped in a high-collared cape with red eyes. ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || k === id) console.log(`\n# ${k} (${s.boss}, ${s.aspect}, ×${s.count}, refs ${s.refs.join('+')})\n${s.prompt}`);
}
