// ART-BOSS-2 Kling 프롬프트 (진홍의 갑주군주 b_crimson · 그리모어 b_grimoire) — 기록/재현용.
// 모델 kling-image-v3_0_omni (image_to_image, img_resolution 2k), 图片1 = assets/portraits/<id>.webp (PNG 로 변환해 업로드).
// 실제로 보낸 프롬프트·생성 ID·채택/기각 이유는 tools/painted/configs/<id>.json 의 kling 블록과 tools/kling/manifest_art-boss-2.json 에 있다.
// 규칙 (docs/art/BOSS_PIPELINE.md §3): 스타일 문구를 맨 앞에, 부품 그룹 하나당 한 장, 평평한 중간 회색 배경, 왼쪽 위 조명, 워터마크(오른쪽 아래) 근처에 물체를 두지 않는다.

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels, keep the bottom-right corner empty.';

const STYLE_CRIMSON = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, deep crimson lacquered steel with dark gunmetal-silver trim, glowing molten orange cracks, no black outlines, not cartoon, not cel-shaded, not 3D render.';
const GORE = 'Grotesque living armour: wherever plates end or crack, the armour is filled with raw glistening dark-red muscle, torn sinew and black veins instead of a body, with thick blood oozing from the seams.';

export const CRIMSON = {
  helm_a: { aspect: '4:3', n: 2, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, the horned great helm of the crimson armour knight from 图片1 alone, strict side view (profile) facing right, two long curved black horns sweeping up and back, a row of short spikes on the crest, a narrow visor slit with two burning ember eyes glowing inside, glowing molten cracks across the crimson steel, rivets and dark silver trim. The helm is empty: at the open bottom neck hole there is no neck, only torn red sinew, dangling blood-soaked strands and smouldering dark fire. The complete helm is fully in frame with a wide empty margin on every side. ${SUFFIX}` },
  torso_a: { aspect: '3:4', n: 2, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, the crimson breastplate torso of 图片1 alone, without head, arms or legs, strict side view (profile) facing right: a massive bulging chest plate and back plate with dark silver edge trim and glowing molten cracks, an open neck hole at the top, an empty round shoulder socket, the waist ends in a ragged opening. ${GORE} Raw red flesh and pulsing veins show through a large crack in the chest. The whole torso fully in frame with empty margin on every side. ${SUFFIX}` },
  pauldron_a: { aspect: '1:1', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, a single huge spiked shoulder pauldron of the crimson armour from 图片1 alone, side view, layered curved crimson plates with a dark silver rim, three long curved steel spikes pointing up and back, glowing molten cracks, and from its open underside hang torn strips of dark chain mail, raw red sinew and dripping blood strands. Fully in frame with empty margin on every side. ${SUFFIX}` },
  arm_a: { aspect: '16:9', n: 2, prompt: `${STYLE_CRIMSON} Subject: a game asset sheet for a 2D cut-out puppet: the separate arm armour pieces of the crimson knight from 图片1 laid out in one row far apart from each other, strict side view, each piece complete and not touching another: 1) an upper arm plate with a spiked elbow cop, 2) a forearm vambrace with a long spike, 3) a heavy black-and-crimson gauntlet clenched into a fist with a hollow round grip hole through the fist (as if holding a pole), 4) a second gauntlet with long clawed steel fingers spread open. ${GORE} ${SUFFIX}` },
  leg_a: { aspect: '16:9', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset sheet for a 2D cut-out puppet: the separate leg armour pieces of the crimson knight from 图片1 laid out in one row far apart from each other, strict side view facing right, each piece complete and not touching another: 1) a thick thigh plate with a big spiked knee cop at its lower end, 2) a shin greave with a spike at the knee, 3) a heavy pointed armoured boot (sabaton) standing flat, toe pointing right. ${GORE} ${SUFFIX}` },
  waist_a: { aspect: '4:3', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, the armoured waist of the crimson knight from 图片1 alone, side view facing right: a wide belt with a horned skull buckle, overlapping crimson fauld and tasset plates hanging down like a short skirt, long torn black cloth tatters hanging behind and between them, blood-soaked sinew dangling from the gaps. Fully in frame with empty margin on every side. ${SUFFIX}` },
  halberd_a: { aspect: '21:9', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, a single huge halberd of the crimson knight from 图片1 lying perfectly straight and horizontal across the image with empty margin at both ends, strict side view: a long dark iron shaft wrapped with worn leather and dark gold rings, a short spike at the left butt end; on the right end a massive jagged crescent axe blade hanging below the shaft, a curved hook on top, and a long spear point pointing right. Blade edges glow molten orange, dried blood and gore on the blade. ${SUFFIX}` },
  // 재생성 (leg_a / waist_a 가 흰 테두리 스티커 그림으로 나와 기각): 스티커 금지 문구 + 왼쪽을 보는 방향 (투구·몸통 그림이 왼쪽을 봄)
  leg_b: { aspect: '16:9', n: 2, prompt: `${STYLE_CRIMSON} Painted like a concept-art illustration, NOT a sticker: no white outline, no white border around the pieces. Subject: a game asset sheet for a 2D cut-out puppet: the two separate leg armour pieces of the crimson knight from 图片1 laid out far apart from each other, strict side view facing left, each piece complete and not touching the other: 1) the upper leg piece, a thick crimson thigh plate ending in a big spiked knee cop at its lower end, 2) the lower leg piece, a shin greave joined to a heavy pointed armoured boot standing flat on its sole, toe pointing left. ${GORE} ${SUFFIX}` },
  waist_b: { aspect: '4:3', n: 1, prompt: `${STYLE_CRIMSON} Painted like a concept-art illustration, NOT a sticker: no white outline, no white border. Subject: a game asset for a 2D cut-out puppet, the armoured waist of the crimson knight from 图片1 alone, three-quarter view facing left: a wide dark belt with a horned skull buckle, overlapping crimson fauld plates with silver rims hanging down like a short skirt, long torn black cloth tatters hanging in the middle, blood-soaked sinew dangling from the gaps. Fully in frame with empty margin on every side. ${SUFFIX}` },
  core_a: { aspect: '1:1', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset for a 2D cut-out puppet, the grotesque living core that fills the empty crimson armour of 图片1, alone without any armour: a huge pulsating heart of clotted blood and raw red muscle, wrapped in black veins and torn sinew, glowing molten orange from deep cracks inside, thick blood strands and severed arteries dangling from its underside, smouldering embers. Front-lit from the upper left, fully in frame with empty margin on every side. ${SUFFIX}` },
  debris_a: { aspect: '16:9', n: 1, prompt: `${STYLE_CRIMSON} Subject: a game asset sheet for a 2D cut-out puppet: 12 separate broken fragments of the crimson armour of 图片1 arranged in a loose 4 by 3 grid with wide empty space between pieces, no piece touches another: jagged crimson plate shards with molten glowing edges, a snapped steel spike, a broken curved black horn tip, a bent clawed gauntlet finger, a torn strip of rivets, a cracked dark silver trim piece, two chunks of clotted blood-soaked flesh with sinew. ${SUFFIX}` },
};

const STYLE_GRIM = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, cracked black-violet leather, aged bone-coloured horn claws, dull silver metal, violet arcane glow, no black outlines, not cartoon, not cel-shaded, not 3D render.';
const GORE_G = 'Grotesque and alive: wet purple flesh, pulsing veins and sticky strands where leather meets flesh.';

export const GRIMOIRE = {
  cover_a: { aspect: '3:4', n: 2, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, the closed front cover of the living grimoire from 图片1 seen strictly straight on (flat frontal view, no perspective, no page block visible): a tall dark leather cover with a carved pentagram and a ring of runes, a dark leather spine band along the left edge, curved bone horn-claws growing out of the right edge and the corners, dull silver corner guards; in the centre one huge wet bloodshot eye with a violet iris, set in a socket of wrinkled purple flesh folds. ${GORE_G} The whole cover fully in frame with empty margin on every side. ${SUFFIX}` },
  eye_a: { aspect: '16:9', n: 2, prompt: `${STYLE_GRIM} Subject: a game asset sheet for a 2D cut-out puppet: three separate parts of the monstrous eye of 图片1 laid out far apart in one row, front view: 1) a wet round eyeball WITHOUT iris and without pupil, only a glossy veined bloodshot white ball with red capillaries, 2) a separate round iris disc, violet fading to amber, with a black vertical slit pupil and a bright highlight, 3) a thick upper eyelid flap of wrinkled wet purple flesh with a row of short black lashes like thorns. ${SUFFIX}` },
  maw_a: { aspect: '3:4', n: 2, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, the first page of the opened living grimoire of 图片1 seen strictly straight on, flat, a single tall yellowed parchment page: in the middle of the page a huge vertical torn mouth splits the paper open — ragged torn-paper lips turning into wet purple flesh gums lined with rows of long needle-sharp yellowed fangs, a dark wet throat with a violet glow deep inside, sticky strands of saliva between the fangs, blood-red runes scrawled all around it. ${GORE_G} The whole page fully in frame with empty margin on every side. ${SUFFIX}` },
  inside_a: { aspect: '3:4', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, the inside of the front cover of the living grimoire of 图片1 seen strictly straight on, flat: a tall dark violet leather endpaper crudely stitched to patches of raw purple flesh with black thread, a large sigil drawn in dried blood, pulsing veins, a row of short hooked fangs along the right edge, dull silver corner guards. The whole cover fully in frame with empty margin on every side. ${SUFFIX}` },
  edge_a: { aspect: '9:16', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, a tall narrow upright strip: the fore-edge of the very thick page block of the grimoire of 图片1 seen straight on from the side, hundreds of yellowed ragged page edges stacked vertically, rows of small sharp teeth and a few curved bone claws growing out between the pages, dark blood and ink stains seeping down. Fully in frame with empty margin on every side. ${SUFFIX}` },
  tentacle_a: { aspect: '21:9', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, a single tentacle of the grimoire of 图片1 (the dark purple clawed tentacle) lying perfectly straight and horizontal across the whole image with empty margin at both ends, strict side view: thick at the left root and tapering to the right, dark violet wet flesh with glowing violet speckles, a row of hooked bone thorns along its top, segmented ridges, ending at the right tip in a cluster of three curved bone claws. ${SUFFIX}` },
  chain_a: { aspect: '21:9', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset for a 2D cut-out puppet, a single heavy old iron chain of 9 big links lying perfectly straight and horizontal across the image with empty margin at both ends, strict side view, dark rusty iron engraved with faint glowing violet runes, and a large ornate iron padlock with a keyhole hanging from the right end. ${SUFFIX}` },
  pages_a: { aspect: '16:9', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset sheet for a 2D cut-out puppet: 8 separate loose torn parchment pages of the grimoire of 图片1 arranged in a loose 4 by 2 grid with wide empty space, no page touches another, each seen flat and straight on: yellowed pages with scrawled black runes, one soaked in blood-red ink, one with a drawn staring eye, one with a torn jagged edge and teeth marks, one burnt at the corner, three small torn scraps. ${SUFFIX}` },
  debris_a: { aspect: '16:9', n: 1, prompt: `${STYLE_GRIM} Subject: a game asset sheet for a 2D cut-out puppet: 12 separate fragments of the destroyed grimoire of 图片1 arranged in a loose 4 by 3 grid with wide empty space, no piece touches another: torn pieces of black leather cover, a broken bone horn-claw, a dull silver corner guard, two snapped iron chain links, a broken padlock, three loose yellowed fangs, two shreds of wet purple flesh with veins. ${SUFFIX}` },
};
