// ART-BOSS-3 Kling 프롬프트 (키메라 호문쿨루스 · 레비아탄 · 태엽 거신). 모델 kling-image-v3_0_omni, image_to_image, 2k.
// 图片1 = 보스 초상화 (assets/portraits/<id>.webp → PNG 업로드). 결과·판정 기록: tools/kling/manifest_art-boss-3.json,
// 부품 설정: tools/painted/configs/<id>.json 의 "kling" 블록. 형식과 규칙: docs/art/BOSS_PIPELINE.md §3.
export const STYLE = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, rich hand-painted texture, dramatic lighting, grotesque and menacing, no black outlines, not cartoon, not cel-shaded, not a 3D render.';
export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels, keep the bottom-right corner empty.';
const P = (s) => `Game asset for a 2D cut-out puppet. ${STYLE} Subject: ${s} ${SUFFIX}`;

export const PROMPTS = {
  // ───────────── 키메라 호문쿨루스 (b_chimera) ─────────────
  b_chimera: {
    torso_a: { aspect: '16:9', count: 2, prompt: P('ONLY the body (torso) of the chimera homunculus from 图片1 as a huge four-legged lion beast, strict side view (profile) facing right, level and horizontal. No head, no neck, no legs, no tail: the neck is a raw stitched stump at the upper right end, the leg joints end in rounded muscle at the shoulder and the haunch, the tail end at the left is a stitched stump. Grotesque alchemical surgery: patchy tawny lion fur torn open in places, thick black thread stitched seams across the flank and along the belly, patches of green snake scales grafted into the flesh along the spine, exposed red muscle and a few bare ribs under torn skin, swollen glowing acid-green veins, three empty brass clamp sockets with raw wounds along the top of the back.') },
    head_a: { aspect: '4:3', count: 2, prompt: P('Strict side view (profile) of the lion head of the chimera from 图片1 facing right, with its huge dark shaggy mane, mouth wide open in a roar showing long yellowed fangs and the dark wet throat, the lower jaw clearly separate at the hinge, glowing acid-green eye, a stitched scar across the face sewn with black thread, patches of grafted green snake scales on the muzzle, green acidic drool. No horns. The neck is cut off just behind the mane.') },
    legs_a: { aspect: '16:9', count: 2, prompt: P('Two separate legs of the lion chimera from 图片1 side by side with wide empty space between them, both in strict side view facing right and hanging almost straight down: on the left a front leg (thick shoulder muscle at the top, elbow, forearm, a huge paw with long black claws planted flat at the bottom), on the right a hind leg (heavy thigh at the top, hock, clawed hind foot planted flat at the bottom). Tawny fur with a black stitched seam around each joint where the leg was grafted on, a few green snake scale patches, raw pink skin at the top where the leg was cut from the body.') },
    goat_a: { aspect: '3:4', count: 2, prompt: P('The goat head of the chimera from 图片1 on a long thin neck, strict side view facing right: the neck rises almost straight up from a raw stitched stump at the bottom of the image, the head sits at the top facing right with huge curling ridged ram horns, glowing acid-green eye with a horizontal pupil, mouth slightly open with a black tongue, a ragged goat beard, sickly grey-brown matted fur, stitches and a green glowing alchemical sigil burned into the brow.') },
    snake_a: { aspect: '21:9', count: 1, prompt: P('A single perfectly straight horizontal length of thick snake body (the living tail of the chimera from 图片1), strict side view, no head: it runs across the whole image from left to right with a small empty margin at both ends, thick at the left end (a stitched stump where it was grafted to the lion rump) and slowly tapering toward the right end which is cut off cleanly. Dark green-black scales on top, pale yellow-green belly plates along the bottom, a few scars and stitched seams, faint green glow between the scales.') },
    snakehead_a: { aspect: '4:3', count: 2, prompt: P('Strict side view (profile) of the snake head at the tip of the chimera tail from 图片1 facing right, mouth wide open showing two long curved venom fangs dripping acid-green venom and the dark throat, the lower jaw clearly separate at the hinge, yellow slit eye, dark green scales with a pale belly, a short piece of neck cut off cleanly at the left.') },
    tubes_a: { aspect: '16:9', count: 1, prompt: P('Three separate tall glass alchemical tubes standing upright side by side with wide empty space between them, each with a heavy brass clamp collar at the bottom and a brass cap at the top, filled with glowing acid-green elixir with bubbles, the glass scratched and grimy, a small bloody pink flesh stump around the bottom of each collar as if torn out of a body.') },
    tubesb_a: { aspect: '16:9', count: 1, prompt: P('Three separate shattered glass alchemical tubes standing upright side by side with wide empty space between them: only the jagged broken lower halves of the glass remain in their heavy brass clamp collars, sharp glass teeth, acid-green elixir spilling and dripping over the brass, a small bloody pink flesh stump around the bottom of each collar.') },
    debris_a: { aspect: '16:9', count: 1, prompt: P('12 separate small pieces from the chimera of 图片1 arranged in a loose 4 by 3 grid with wide empty space between pieces, no piece touches another: sharp shards of broken green glass, bloody clumps of tawny fur, torn patches of green snake skin, chunks of raw flesh with black stitches, a broken brass clamp, a snapped fang.') },
  },
  // ───────────── 레비아탄 (b_leviathan) ─────────────
  b_leviathan: {
    head_a: { aspect: '4:3', count: 2, prompt: P('Strict side view (profile) of the head of the sea serpent from 图片1 facing right, mouth wide open showing rows of long needle teeth, a second ring of lamprey-like hooked teeth deep in the dark throat, the lower jaw clearly separate at the hinge, a crown of long pale bone horns sweeping back, translucent teal fin frills behind the head, glowing cyan bioluminescent spots along the head, a pale glowing eye, barnacles, scars and slime. The neck is cut off at the left behind the frills.') },
    body_a: { aspect: '21:9', count: 2, prompt: P('A single perfectly straight horizontal length of the body of the sea serpent from 图片1, strict side view, no head, no tail fin, no dorsal fin: it runs across the whole image from left to right with a small empty margin at both ends, uniform thickness along its whole length. Dark teal-green armored scales on the upper half, pale ribbed belly plates along the bottom, a row of glowing cyan bioluminescent spots along the flank, barnacles and old bite scars, one torn wound with pale ribs and red flesh showing, clinging parasitic lamprey worms.') },
    fins_a: { aspect: '16:9', count: 1, prompt: P('8 separate dorsal fin spines of the sea serpent from 图片1 standing upright in one row with wide empty space between them, each with its straight base at the bottom: translucent teal webbed membranes stretched between sharp pale bone spines, some torn and ragged with holes, different heights, glowing cyan tips.') },
    fluke_a: { aspect: '16:9', count: 1, prompt: P('Two separate parts of the sea serpent from 图片1 with wide empty space between them: on the left the huge forked tail fin (fluke) seen from the side, its root at the bottom centre and the two ragged lobes spreading up and outward, torn translucent teal webbing over pale bone rays with glowing cyan edges; on the right a single pectoral fin (root at the left, spreading to the right), same material.') },
    debris_a: { aspect: '16:9', count: 1, prompt: P('12 separate small pieces from the sea serpent of 图片1 arranged in a loose 4 by 3 grid with wide empty space between pieces, no piece touches another: large dark teal scales, broken needle teeth, a shred of torn fin membrane, a barnacle cluster, a chunk of pale flesh with a glowing cyan spot, a broken bone horn tip.') },
  },
  // ───────────── 태엽 거신 (b_colossus) ─────────────
  b_colossus: {
    torso_a: { aspect: '1:1', count: 2, prompt: P('Front view (facing the viewer, symmetrical) of ONLY the torso and waist of the clockwork colossus from 图片1: no head, no arms, no legs. A massive riveted brass and rusted iron chest shell with a large round empty dark socket in the centre of the chest (the clock face is separate), a glowing orange furnace grate in the belly, two iron chimneys on top of the shoulders, round empty shoulder sockets at both sides, a heavy gearbox waist below with the leg joints cut off. Grotesque: blood-red rust, dried blood streaks, bundles of black pipes and cables like sinews, human bones and a trapped rib cage visible between the plates.') },
    head_a: { aspect: '1:1', count: 2, prompt: P('Front view (facing the viewer, symmetrical) of the head of the clockwork colossus from 图片1: a spiked rusted iron helmet with two curved horns and a tall central spike, inside the open visor a grinning cracked human skull with glowing red eyes and a few rotten teeth, a riveted brass collar and a small neck gear below, dried blood running from the eye sockets.') },
    arm_a: { aspect: '16:9', count: 2, prompt: P('The separate pieces of ONE arm of the clockwork colossus from 图片1 laid out apart from each other in a row with wide empty space between them, all in front view: a spiked iron shoulder pauldron, a riveted brass upper-arm cylinder (vertical), a large brass elbow gear, an iron forearm cylinder with a steel piston rod (vertical), and a huge iron fist made of spiked gear knuckles with clawed fingers.') },
    leg_a: { aspect: '16:9', count: 2, prompt: P('The separate pieces of ONE leg of the clockwork colossus from 图片1 laid out apart from each other in a row with wide empty space between them, all in front view: a riveted brass thigh cylinder (vertical), a brass knee gear, an iron shin with a steel piston rod (vertical), and a heavy spiked armoured iron foot seen from the front.') },
    clock_a: { aspect: '16:9', count: 1, prompt: P('Two separate objects from the chest of the clockwork colossus of 图片1 with wide empty space between them, both seen straight from the front: on the left a large round clock face with a cream enamel dial, black roman numerals and a heavy toothed brass bezel, without clock hands; on the right the exposed furnace core, a white-hot glowing sphere of molten fire held in a black iron cage with a still-beating human heart wired into it by copper cables.') },
    gears_a: { aspect: '16:9', count: 1, prompt: P('Separate brass machine parts from 图片1 with wide empty space between them, all seen straight from the front: four round brass gears of different sizes with spokes and teeth (flat, facing the viewer), a long ornate vertical brass pendulum rod, and a huge crescent-moon shaped steel pendulum blade with a sharp bloodstained edge.') },
    debris_a: { aspect: '16:9', count: 1, prompt: P('12 separate small pieces from the clockwork colossus of 图片1 arranged in a loose 4 by 3 grid with wide empty space between pieces, no piece touches another: bent riveted brass plates, rusted iron shards, small gears, coiled springs, broken pipes, bolts, a cracked piece of a human skull.') },
  },
};
