// EX-BOSS Kling 프롬프트 (외전 21장 보스: 아르겐 b_argen — 공허에 물든 은룡)
// 모델 kling-image-v3_0_omni · img_resolution 2k (image_to_image 기본값이 4k 이므로 반드시 2k 를 넘긴다).
//  · 초상화: text_to_image 3:4 (기존 2부 보스 초상화와 같은 꼬리말) → assets/portraits/b_argen.webp
//  · 부품: image_to_image, 图片1 = 초상화 (assets/portraits/b_argen.webp → PNG 업로드). 템플릿: docs/art/BOSS_PIPELINE.md §3
// 퍼핏 방향: 옆모습, 오른쪽을 본다 (로직 c_argen.js 의 몸 지역 좌표 +x = 머리 쪽).
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_ex-boss.json 과 configs/b_argen.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/ex-boss.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No smoke, no mist, no clouds, no fire, no sparks, no lightning bolts, no particles, no glow haze, no magic effects around the object.';
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';
const PORTRAIT_TAIL = 'Dark gothic horror boss monster concept art, majestic yet grotesque, highly detailed painterly digital illustration, dramatic lighting, dark background, video game boss portrait, a single creature, no text, no watermark.';

const AGX = 'jagged glossy obsidian-black void crystals with deep violet translucent edges and faint inner violet light';
const AG = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, gleaming silver-white dragon scales with cold pale-blue highlights, pale ivory horns and claws, thin dark violet corruption veins in a few cracked scales, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';

/** shot → { tool, aspect, count, refs (image_1 = 초상화, 그 뒤 = 이미 채택한 결과), prompt } */
export const SHOTS = {
  ag_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Argen, a colossal majestic silver sky dragon corrupted by the void, seen from the side facing right, a long elegant serpentine neck, a noble horned head with swept-back pale ivory horns, gleaming silver-white scales like polished moonlit armour, vast outstretched silver wings with pale blue translucent membranes, jagged black-violet void crystals erupting from its shoulders, spine, wings and tail like a spreading infection, cracked scales and dark violet veins around the crystals, a glowing dark violet void core crystal embedded in its chest, eyes glowing violet, a long tail ending in a silver fin, flying above the clouds over a ruined white marble sky sanctuary at dusk. ${PORTRAIT_TAIL}` },

  ag_head: { tool: 'image_to_image', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${AG} Strict side view (profile) of the head of the silver dragon from 图片1 alone, facing right: a long noble dragon head with silver-white scales, two long swept-back pale ivory horns and a crest of small spikes along the back of the skull, the mouth wide open showing sharp ivory teeth in both jaws, the lower jaw clearly separate and dropped open at the hinge with a dark empty gap and a dark red throat between the jaws, a narrow almond eye socket with a closed dark eyelid, thin dark violet corruption veins under the scales of the cheek, NO crystals on the head, the neck cut flat at the lower left. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_body: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${AG} Strict side view facing right of the body of the silver dragon from 图片1 WITHOUT head, WITHOUT neck, WITHOUT wings, WITHOUT legs and WITHOUT tail: a powerful barrel-shaped torso covered in overlapping silver-white scales, pale ivory belly plates along the bottom, a row of short sharp ivory dorsal spikes along the spine ridge on top, thin dark violet corruption veins under the cracked scales of the back, NO crystals on the body, a round cracked dark socket in the chest at the right side with violet veins spreading from it (the socket is empty and dark), the thick neck stump cut flat at the upper right, the tail stump cut flat at the left, flat stumps where the legs and wings attach. ${NOFX} ${NOHALO} ${SUFFIX}` },
  // ── v2 재생성 (첫 묶음 검수 뒤): ag_body 두 장이 모두 '끝이 뚫린 관' — 'stump cut flat' 문구가 단면 구멍으로 그려졌다 ──
  ag_body2: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, gleaming silver-white dragon scales with cold pale-blue highlights, pale ivory spikes, thin dark violet corruption veins in a few cracked scales, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet. Strict side view facing right of the massive torso of the silver dragon from 图片1 on its own: a solid closed rounded body shaped like a large horizontal egg, the rounded deep chest at the right end, the body narrowing smoothly toward the hips at the left end, the outline is completely closed and smooth all around, NO openings, NO holes, NO hollow tube ends, NO pipe, NO cut cross-sections, no head, no neck, no wings, no legs, no tail. Overlapping silver-white scales on the back and flanks, large pale ivory belly plates along the whole underside, a row of short sharp ivory dorsal spikes along the top of the back, a web of thin glowing violet corruption veins spreading over the chest at the lower right. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_necktail: { tool: 'image_to_image', aspect: '21:9', count: 2, refs: ['portrait'], prompt: `${AG} Two separate long body pieces of the silver dragon from 图片1, each lying perfectly straight and level across the whole image width, one above the other with wide empty space between them, strict side view, no piece touches another: 1) on top, a long straight dragon neck, thick and cut flat at the RIGHT end (shoulder), slightly thinner and cut flat at the LEFT end (head), overlapping silver-white scales on top, a row of pale ivory belly plates along the bottom edge, a row of small sharp dorsal spikes along the top, NO crystals; 2) below, a long straight dragon tail, thick and round and cut flat at the RIGHT end, tapering smoothly to the LEFT, silver-white scales on top, pale ivory belly plates along the bottom edge, small dorsal spikes along the top, thin dark violet corruption veins under the scales, NO crystals, ending on the LEFT in a broad leaf-shaped silver tail fin. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_wing: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${AG} A single huge dragon wing of the silver dragon from 图片1 alone, spread wide open, strict side view: the shoulder root of the wing is at the lower RIGHT, the thick scaled wing arm rises up and to the left to a knobbly wrist with a small ivory claw near the upper middle of the image, four long thin finger bones fan out from the wrist to the LEFT and downward, between the fingers a pale silver-blue translucent membrane with a few small tears, the membrane's lower edge is scalloped between the finger tips, the scaled wing arm is silver-white, thin dark violet corruption veins in the membrane near the arm, NO crystals on the wing. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_legs: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${AG} Four separate leg pieces of the silver dragon from 图片1 laid out apart from each other in one row with wide empty space between them, no piece touches another: 1) a thick muscular scaled hind thigh, vertical, 2) a scaled hind shin with an ankle, vertical, 3) a big dragon hind foot with four long curved ivory talons spread open, pointing down, 4) a smaller scaled front leg with a clawed hand, bent at the elbow. Silver-white scales. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_crystals: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${AG} ${AGX}. Eight separate clusters of jagged black-violet void crystals arranged in a loose grid with wide empty space between them, no piece touches another, each cluster grows out of a flat base at the bottom: two tall clusters of three long shards, three medium clusters, two small single shards, and one round faceted dark violet heart crystal like a gem with a bright violet glowing centre. Glossy obsidian-black surfaces with deep violet translucent edges and thin bright violet cracks. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ag_debris: { tool: 'image_to_image', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${AG} ${AGX}. About ten separate broken pieces arranged in a loose grid with wide empty space between pieces, no piece touches another: silver-white dragon scales of different sizes, shattered black-violet void crystal shards, a broken ivory horn tip, a broken ivory claw. ${NOFX} ${NOHALO} ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || id === k) console.log(`── ${k} (${s.tool} ${s.aspect} ×${s.count})\n${s.prompt}\n`);
}
