// EX2-BOSS Kling 프롬프트 (외전 22장 보스: 둥지어미 / 네메인 b_nemain + 수호신 무닌 초상화) — docs/specs/ex_s22.md §2.2
// 모델 kling-image-v3_0_omni · img_resolution 2k (image_to_image 기본값이 4k 이므로 반드시 2k 를 넘긴다).
//  · 초상화: text_to_image 3:4 (기존 2부 보스 초상화와 같은 꼬리말) → assets/portraits/b_nemain.webp
//  · form2 초상화: image_to_image 3:4, 图片1 = 가면 초상화 (같은 구도) → assets/portraits/b_nemain2.webp
//  · 부품: image_to_image, 图片1 = 가면 초상화 (PNG 업로드). 템플릿: docs/art/BOSS_PIPELINE.md §3
//  · 무닌 초상화: text_to_image 3:4 (수호신 초상화와 같은 꼬리말 — tools/kling/manifest_companions.json) → assets/portraits/cmp_gd_munin.webp
// 퍼핏 방향: 옆모습, 오른쪽을 본다 (로직 e_nemain.js 의 몸 지역 좌표 +x = facing).
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_ex2-boss.json 과 configs/b_nemain.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/ex2-boss.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No smoke, no mist, no clouds, no fire, no sparks, no particles, no glow haze, no magic effects around the object.';
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';
const BOSS_TAIL = 'Dark gothic horror boss concept art, elegant yet menacing and grotesque, highly detailed painterly digital illustration, dramatic lighting, dark background, video game boss portrait, a single character, no text, no watermark.';
const GUARD_TAIL = 'Dark gothic fantasy creature portrait, highly detailed painterly digital illustration, dramatic rim lighting, dark atmospheric background with crimson moonlight, video game companion card art, no text, no letters, no watermark.';

const NM = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, glossy black leather and black crow feathers with a cold blue-violet sheen, cold blue moonlight highlights, deep crimson accents, pale skin, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';

/** shot → { tool, aspect, count, refs (image_1 = 가면 초상화), prompt } */
export const SHOTS = {
  nm_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Nemain, the Nest Mother of the Crow Society, a tall gaunt severe woman in her late forties, seen in three-quarter view, the upper half of her face hidden by a cracked black-lacquered crow-beak half mask with a long sharp black beak over her nose and narrow eye holes with a faint red glint, her thin pale lips and pale chin visible below the mask, long black hair streaked with silver tied back, a huge mantle of thousands of glossy black crow feathers draped over her shoulders and dragging on the ground, its inner lining deep crimson red, many small red crow eyes glinting among the feathers of the mantle, a close-fitting black leather assassin suit with silver buckles, crow tattoos on her neck and wrists, two long black daggers shaped like crow beaks held crossed in front of her chest, black crows circling in the dark behind her, standing under a cracked bronze bell in a ruined stone bell tower at night, cold blue moonlight rim light. ${BOSS_TAIL}` },
  nm_portrait2: { tool: 'image_to_image', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `Edit 图片1: keep exactly the same woman, the same pose, composition, framing, camera angle, feather mantle, crossed crow-beak daggers, bell tower, crows and lighting, but her black crow-beak mask has cracked and half of it has broken away: the left half of the mask is gone and broken shards of black lacquer fall beside her face, revealing half of her bare face: a pale stern beautiful face of a woman in her late forties with a thin old scar across the cheek and one bright crimson-red eye blazing with sorrow and anger, strands of black hair streaked with silver loosened around her face; the right half of her face is still covered by the cracked beak mask. ${BOSS_TAIL}` },

  nm_full: { tool: 'image_to_image', aspect: '9:16', count: 2, refs: ['portrait'], prompt: `${NM} Strict side view (profile) of the whole body of the woman from 图片1 WITHOUT her feather mantle, standing upright and facing right, the full figure from the top of the head to the boots: the black crow-beak half mask on her face, black hair streaked with silver pulled back into a low knot, a tight black leather assassin suit with silver buckles across the chest, a crow tattoo on the side of the neck, a narrow waist with a silver-buckled belt, slim legs in tight black leather trousers and tall black boots, one foot forward and one foot back in a calm stance so both legs are clearly visible. No arms (the shoulders end in rounded stumps), no mantle, no cape, no feathers on the body, no daggers, no crows. ${NOFX} ${NOHALO} ${SUFFIX}` },
  nm_heads: { tool: 'image_to_image', aspect: '4:3', count: 2, refs: ['portrait'], prompt: `${NM} Two separate heads of the woman from 图片1 side by side with wide empty space between them, both in strict side view (profile) facing right, the same size: 1) on the left, her head wearing the black-lacquered crow-beak half mask: the long sharp black beak over her nose, a fine crack running across the lacquer, a narrow eye hole with a small red glint, her thin pale lips and chin below the mask, black hair streaked with silver pulled back into a low knot at the nape; 2) on the right, the same head WITHOUT any mask: the pale stern face of a woman in her late forties with a straight nose, high cheekbones, a thin old scar on the cheek, a bright crimson-red eye, thin lips, the same black hair streaked with silver pulled back into a low knot. Each head is cut cleanly at the base of the neck. No collar, no feathers, no body. ${NOFX} ${NOHALO} ${SUFFIX}` },
  nm_arms: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${NM} Five separate pieces of the woman from 图片1 laid out apart from each other in two rows with wide empty space between them, no piece touches another, each lying straight and horizontal and pointing right: 1) an upper arm in a tight black leather sleeve with a silver buckle strap, from the rounded shoulder on the left to the elbow on the right; 2) a forearm in a black leather bracer with a small crow tattoo on the pale wrist, ending in a slender pale hand clenched in a tight fist around an empty round hole as if gripping a pole; 3) the same kind of forearm ending in an open pale hand with long fingers spread; 4) and 5) two long black daggers shaped like crow beaks, each a slightly curved black steel blade with a thin silver edge, a wrapped black leather grip and a small silver crow-skull pommel, lying horizontal with the point to the right. ${NOFX} ${NOHALO} ${SUFFIX}` },
  nm_cloak: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${NM} The huge feather mantle of the woman from 图片1 alone, spread wide open like a pair of crow wings and seen flat from behind: gathered at the top centre (the collar at the shoulders), thousands of glossy black crow feathers fanning out to the left and the right and hanging down in long ragged layered points like wing feathers, the long middle back panel hanging straight down to a ragged feathered hem, the deep crimson red silk lining showing along the inner edges, a few small red crow eyes peeking out between the feathers. Only the mantle, no person, no head, no arms. ${NOFX} ${NOHALO} ${SUFFIX}` },
  nm_crows: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${NM} Four separate black crows from 图片1 laid out apart from each other in one row with wide empty space between them, no piece touches another, all in strict side view flying to the right, the same size: 1) wings raised high up, 2) wings swept fully down, 3) wings half spread gliding, 4) diving with the wings folded back and the beak forward. Glossy blue-black feathers, ragged wing tips, a sharp black beak, a small crimson red eye. ${NOFX} ${NOHALO} ${SUFFIX}` },
  nm_debris: { tool: 'image_to_image', aspect: '1:1', count: 1, refs: ['portrait'], prompt: `${NM} About nine separate pieces from 图片1 arranged in a loose grid with wide empty space between pieces, no piece touches another: the two broken halves of the black-lacquered crow-beak half mask (one half with the long beak, the other half with an eye hole), three single long black crow feathers with a blue sheen, one black feather with a crimson underside, one long black crow-beak dagger lying horizontal, and two small broken shards of black lacquer. ${NOFX} ${NOHALO} ${SUFFIX}` },

  munin_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Munin, an old wise raven guardian, a large glossy black crow with a blue-violet sheen on its feathers seen in profile with its head turned toward the viewer, a few ragged grey feathers on the crown of its head showing its great age, deep black eyes rimmed with a thin crimson ring, a faded red cloth ribbon tied around one leg, a thick strong black beak, perched on top of a small weathered stone gravestone with faint worn carvings, in a misty hillside graveyard of nameless graves under a full moon, a calm knowing presence. ${GUARD_TAIL}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || id === k) console.log(`── ${k} (${s.tool} ${s.aspect} ×${s.count})\n${s.prompt}\n`);
}
