// EX3-BOSS Kling 프롬프트 (외전 23장 보스: 늑대잡이 하겐 / 은빛 늑대 b_hagen) — docs/specs/ex_s23.md §2.2
// 모델 kling-image-v3_0_omni · img_resolution 2k (image_to_image 기본값이 4k 이므로 반드시 2k 를 넘긴다).
//  · 초상화: text_to_image 3:4 (기존 2부 보스 초상화와 같은 꼬리말) → assets/portraits/b_hagen.webp
//  · form2 초상화: image_to_image 3:4, 图片1 = 사람 초상화 (같은 구도) → assets/portraits/b_hagen2.webp
//  · 부품: image_to_image, 图片1 = 사람 초상화 (PNG 업로드), 늑대 부품은 图片2 = 늑대 초상화. 템플릿: docs/art/BOSS_PIPELINE.md §3
// 퍼핏 방향: 옆모습, 오른쪽을 본다 (로직 e_hagen.js 의 몸 지역 좌표 +x = facing).
// 상한 22장 · 44크레딧 (재시도 포함). 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_ex3-boss.json 과 configs/b_hagen.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/ex3-boss.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No snow, no smoke, no mist, no fire, no sparks, no particles, no glow haze, no magic effects around the object.';
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';
const BOSS_TAIL = 'Dark gothic horror boss concept art, weathered, melancholic yet menacing, highly detailed painterly digital illustration, dramatic lighting, dark background, video game boss portrait, a single character, no text, no watermark.';

const HG = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, worn dark-brown leather, tarnished silver, coarse silver-grey wolf fur, cold blue moonlight highlights, warm amber accents, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const WOLF = 'The werewolf is the same creature as in 图片2: a huge hunched silver-grey werewolf with a long wolf muzzle and amber-yellow eyes.';

/** shot → { tool, aspect, count, refs (image_1 = 사람 초상화, image_2 = 늑대 초상화), prompt } */
export const SHOTS = {
  hg_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Hagen the old wolf hunter, a tall gaunt weathered man around sixty years old, seen in three-quarter view, a battered wide-brimmed leather hat, a grizzled grey beard and an old scar across his cheek, his eyes glowing a feral amber-yellow like a wolf's eyes, a long snow-crusted dark-brown leather hunting coat, a bandolier of silver bullets across his chest, a long old hunting rifle held across his body, a hunting knife at his belt, silver-grey wolf hairs bristling on the backs of his bare weathered hands, standing in a snowstorm at night in the courtyard of a frozen ruined monastery on a mountain pass, a full moon behind thin clouds, cold blue moonlight rim light and a warm amber glow from a dying campfire below. ${BOSS_TAIL}` },
  hg_portrait2: { tool: 'image_to_image', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `Transform the old hunter of 图片1 into a werewolf. Keep the same composition, framing, camera angle, snowstorm, frozen monastery, full moon and lighting, but the man is gone: in his place stands a huge hunched silver-grey werewolf, a towering wolf-man with a long wolf muzzle full of fangs, thick shaggy silver-grey fur, a hunched back, long clawed hands, the torn shreds of the same dark-brown leather hunting coat still hanging from his shoulders and the coat collar around his thick neck, the same bandolier of silver bullets across his furred chest; his amber-yellow wolf eyes still hold a sad human light. ${BOSS_TAIL}` },

  hg_full: { tool: 'image_to_image', aspect: '9:16', count: 2, refs: ['portrait'], prompt: `${HG} Strict side view (profile) of the whole body of the old hunter from 图片1, standing upright and facing right, the full figure from the top of the hat to the boots: the battered wide-brimmed hat, grey beard, a long dark-brown leather hunting coat closed and belted at the waist, its long skirt reaching to the knees and split at the back, the bandolier of silver bullets across the chest, dark trousers and tall worn leather boots, one foot forward and one foot back in a calm stance so both legs are clearly visible below the coat. No arms (the shoulders end in rounded stumps), no rifle, no knife, no hands. ${NOFX} ${NOHALO} ${SUFFIX}` },
  hg_beast: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait', 'portrait2'], prompt: `${HG} ${WOLF} Strict side view (profile) of the whole body of the werewolf from 图片2, standing on all fours ready to pounce and facing right: a hunched back, a deep chest, shaggy silver-grey fur, the torn shreds of the dark-brown leather hunting coat from 图片1 hanging from its shoulders and back, the bandolier of silver bullets across its chest, powerful digitigrade hind legs with the reverse-bent ankle clearly visible, long front legs with big clawed paws, a long bushy tail stretched straight out behind. ${NOFX} ${NOHALO} ${SUFFIX}` },
  hg_heads: { tool: 'image_to_image', aspect: '4:3', count: 1, refs: ['portrait', 'portrait2'], prompt: `${HG} ${WOLF} Three separate heads side by side in one row with wide empty space between them, all in strict side view (profile) facing RIGHT, each cut cleanly at the base of the neck: 1) on the left, the head of the old hunter from 图片1 wearing the battered wide-brimmed leather hat, grey beard, an old scar on the cheek, a glowing amber-yellow wolf eye, with the turned-up leather coat collar; 2) in the middle, the head of the werewolf from 图片2 with the long muzzle and the mouth closed, ears laid back, amber-yellow eye, shaggy silver-grey fur and a scrap of the leather coat collar around the neck; 3) on the right, the same werewolf head with the jaws wide open in a roar showing long fangs and a dark throat. No body. ${NOFX} ${NOHALO} ${SUFFIX}` },
  hg_arms: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait', 'portrait2'], prompt: `${HG} ${WOLF} Six separate pieces laid out apart from each other in two rows with wide empty space between them, no piece touches another, each lying straight and horizontal and pointing right: top row: 1) the upper arm of the old hunter from 图片1 in the dark-brown leather coat sleeve, from the rounded shoulder on the left to the elbow on the right; 2) his forearm in the leather coat sleeve ending in a gloved hand clenched in a tight fist around an empty round hole as if gripping a pole; 3) his long old hunting rifle with a dark wooden stock and a long iron barrel, muzzle to the right; bottom row: 4) a heavy hunting knife with a broad steel blade and a bone handle, point to the right; 5) the upper foreleg of the werewolf from 图片2, thick shaggy silver-grey fur, from the shoulder on the left to the elbow on the right; 6) the lower foreleg of the werewolf ending in a huge paw with long black claws pointing right. ${NOFX} ${NOHALO} ${SUFFIX}` },
  hg_props: { tool: 'image_to_image', aspect: '1:1', count: 1, refs: ['portrait'], prompt: `${HG} About seven separate small objects belonging to the old hunter from 图片1 arranged in a loose grid with wide empty space between them, no piece touches another: an open silver-steel snare trap with toothed jaws seen from the side, a single long silver rifle bullet lying horizontal, a curved hunting horn made of a bull horn with a brass mouthpiece, two torn ragged scraps of dark-brown leather coat, and one tuft of shaggy silver-grey wolf fur. ${NOFX} ${NOHALO} ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || id === k) console.log(`── ${k} (${s.tool} ${s.aspect} ×${s.count})\n${s.prompt}\n`);
}
