// EX4-BOSS Kling 프롬프트 (외전 24장 보스: 엘제베트 / 시든 신부 b_bride + 수호신 베스퍼 초상화) — docs/specs/ex_s24.md §2.2
// 모델 kling-image-v3_0_omni · img_resolution 2k (image_to_image 기본값이 4k 이므로 반드시 2k 를 넘긴다).
//  · 초상화: text_to_image 3:4 (기존 2부 보스 초상화와 같은 꼬리말) → assets/portraits/b_bride.webp
//  · form2 초상화: image_to_image 3:4, 图片1 = 귀부인 초상화 (같은 구도) → assets/portraits/b_bride2.webp
//  · 부품: image_to_image, 图片1 = 귀부인 초상화 (PNG 업로드), 노파 부품은 图片2 = 노파 초상화. 템플릿: docs/art/BOSS_PIPELINE.md §3
//  · 베스퍼 초상화: text_to_image 3:4 (수호신 초상화와 같은 꼬리말 — ex2-boss.mjs munin_portrait) → assets/portraits/cmp_gd_vesper.webp
// 퍼핏 방향: 옆모습, 오른쪽을 본다 (로직 e_bride.js 의 몸 지역 좌표 +x = facing).
// 상한 22장 · 44크레딧 (재시도 포함, 보스 + 초상화 셋). 계획 13장 · 26크레딧.
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_ex4-boss.json 과 configs/b_bride.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/ex4-boss.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No smoke, no mist, no blood splashes, no fire, no sparks, no particles, no floating petals, no glow haze, no magic effects around the object.';
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';
const BOSS_TAIL = 'Dark gothic horror boss concept art, elegant yet menacing and grotesque, highly detailed painterly digital illustration, dramatic lighting, dark background, video game boss portrait, a single character, no text, no watermark.';
const GUARD_TAIL = 'Dark gothic fantasy creature portrait, highly detailed painterly digital illustration, dramatic rim lighting, dark atmospheric background with crimson moonlight, video game companion card art, no text, no letters, no watermark.';

const BD = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, deep crimson silk and black lace, tarnished gold, pale ivory porcelain skin, warm candle highlights, blood-red rose accents, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const CRONE = 'The withered crone is the same creature as in 图片2: a withered undead bride with a gaunt cracked skull-like porcelain face, sunken glowing crimson eyes, long snow-white hair and long golden claw-like nails, wearing the rotted rags of the same crimson and black gown.';   // bd_portrait2 #1 (채택본) 에 맞춰 고침 — 해골 같은 금 간 얼굴 · 금빛 손톱

/** shot → { tool, aspect, count, refs (image_1 = 귀부인 초상화, image_2 = 노파 초상화), prompt } */
export const SHOTS = {
  bd_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Elzebet, the first bride of Count Dracula, an ageless pale vampire noblewoman whose face is eerily smooth and flawless like polished porcelain, seen in three-quarter view, a crown of fresh blood-red roses set on a long sheer black lace veil that falls over her shoulders, cold crimson eyes, dark red lips with a cruel faint smile, long black hair, an elegant high-collared close-fitting gown of deep crimson silk and black lace with a very long train pooling on the floor behind her, a tarnished golden goblet raised in her left hand, a whip made of a thorny rose vine coiled in her right hand, standing in front of a ruined gothic convent chapel at night whose walls and broken altar are overgrown with blood-red roses, a dark pool of blood glinting below the altar, candlelight and crimson moonlight. ${BOSS_TAIL}` },
  bd_portrait2: { tool: 'image_to_image', aspect: '3:4', count: 2, refs: ['portrait'], prompt: `Edit 图片1: keep the same composition, framing, camera angle, ruined rose-covered chapel, crown of roses, black lace veil, golden goblet and lighting, but the borrowed years have caught up with her all at once: she is now an emaciated ancient withered crone, her face like cracked old porcelain with deep fissures running across the cheeks and forehead, sunken eyes still glowing crimson, her long hair turned completely snow-white, the roses in her crown wilted and dark, the black lace veil burnt and tattered, her crimson and black gown rotted into hanging rags, bony hands with very long yellowed nails clutching the golden goblet, her body floating a little above the floor with the ragged train drifting below her instead of feet. ${BOSS_TAIL}` },

  bd_full: { tool: 'image_to_image', aspect: '9:16', count: 2, refs: ['portrait'], prompt: `${BD} Strict side view (profile) facing RIGHT, her nose points to the right edge of the image, of the whole body of the noblewoman from 图片1 WITHOUT ARMS: both arms are completely missing, the shoulders end in rounded stumps of crimson silk, so the whole side of the close-fitting bodice is visible. The full figure from the crown of red roses to the floor: the long sheer black lace veil hanging down her back, a slender waist, the full crimson and black lace skirt reaching the floor and a very long train spread out flat on the floor far behind her to the left. Standing upright and calm. No hands, no goblet, no whip, no white border, no sticker outline. ${NOFX} ${NOHALO} ${SUFFIX}` },
  bd_crone: { tool: 'image_to_image', aspect: '9:16', count: 2, refs: ['portrait', 'portrait2'], prompt: `${BD} ${CRONE} Strict side view (profile) facing RIGHT of the whole body of the withered crone from 图片2 floating in the air WITHOUT ARMS: both arms are completely missing, the bony shoulders end in rounded stumps wrapped in rags. A hunched bony back, the head thrust forward, long snow-white hair hanging down her back, the rotted crimson and black rags of the gown hanging from her body and fluttering below her in three long torn ragged strips instead of legs and feet, nothing touches the ground. No hands, no goblet, no white border, no sticker outline. ${NOFX} ${NOHALO} ${SUFFIX}` },
  bd_heads: { tool: 'image_to_image', aspect: '4:3', count: 1, refs: ['portrait', 'portrait2'], prompt: `${BD} ${CRONE} Three separate heads side by side in one row with wide empty space between them, all in strict side view (profile) facing RIGHT (every nose points to the right edge of the image), the same size, each cut cleanly at the base of the neck: 1) on the left, the young flawless head of the noblewoman from 图片1 with the crown of red roses and the long black lace veil falling behind her head to the nape; 2) in the middle, the same face without the veil, half cracked like broken porcelain, fine dark cracks spreading over the cheek, her black hair turning white at the roots; 3) on the right, the withered crone head from 图片2 with deep cracks over the whole face, a sunken crimson eye, long snow-white hair hanging behind and a crown of wilted dark roses. No body. ${NOFX} ${NOHALO} ${SUFFIX}` },
  bd_arms: { tool: 'image_to_image', aspect: '16:9', count: 1, refs: ['portrait', 'portrait2'], prompt: `${BD} ${CRONE} Five separate pieces laid out apart from each other in two rows with wide empty space between them, no piece touches another, each lying straight and horizontal and pointing right, no person, no body, no head: top row: 1) a slender upper arm in a tight crimson silk sleeve with black lace at the shoulder, from the rounded shoulder on the left to the elbow on the right; 2) a slender forearm in a crimson sleeve with a black lace cuff, ending in a pale elegant hand clenched in a tight fist around an empty round hole as if gripping a pole; 3) the same kind of forearm ending in an open pale hand with the palm turned up and the fingers curled as if holding a cup; bottom row: 4) an emaciated bony upper arm of the crone from 图片2 wrapped in rotted rags; 5) her bony forearm ending in a skeletal hand with long golden claw-like nails, fingers spread like claws. ${NOFX} ${NOHALO} ${SUFFIX}` },
  bd_props: { tool: 'image_to_image', aspect: '1:1', count: 1, refs: ['portrait'], prompt: `${BD} About nine separate small objects belonging to the noblewoman from 图片1 arranged in a loose grid with wide empty space between them, no piece touches another: an ornate tarnished golden goblet seen from the side, three jagged broken shards of the same golden goblet, a single fresh blood-red rose with a short stem lying horizontal, one straight horizontal segment of a thorny rose vine with sharp thorns, two single withered dark red rose petals, and one torn scrap of black lace veil. ${NOFX} ${NOHALO} ${SUFFIX}` },

  vesper_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Vesper, a small black bat guardian, a tiny bat with soft black fur, translucent deep crimson wing membranes, small white fangs and glowing red eyes, a little red silk ribbon tied in a bow around one of its ears, hanging upside down from the frame of an old gothic window by its feet, holding in its mouth a folded letter sealed with a red wax seal stamped with a rose, a full moon and wilting roses outside the window behind it, a gentle loyal presence. ${GUARD_TAIL}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || id === k) console.log(`── ${k} (${s.tool} ${s.aspect} ×${s.count})\n${s.prompt}\n`);
}
