// EX5-BOSS Kling 프롬프트 (외전 25장 보스: 카론 / 사신의 마부 b_charon + 탈것 모르겐 초상화) — docs/specs/ex_s25.md §2.2
// 모델 kling-image-v3_0_omni · img_resolution 2k (image_to_image 기본값이 4k 이므로 반드시 2k 를 넘긴다).
//  · 초상화: text_to_image 3:4 (기존 2부 보스 초상화와 같은 꼬리말) → assets/portraits/b_charon.webp (form2 도 같은 초상화, §9-6)
//  · 모르겐 초상화: text_to_image 3:4 (탈것 초상화와 같은 틀 — manifest_companions.json cmp_mt_ignis) → assets/portraits/cmp_mt_morgen.webp
//  · 부품: image_to_image, 图片1 = 카론 초상화 (PNG 업로드). 템플릿: docs/art/BOSS_PIPELINE.md §3
// 퍼핏 방향: 옆모습, 오른쪽을 본다 (로직 e_charon.js 의 몸 지역 좌표 +x = facing; 마차는 끌채·마부석이 오른쪽).
// 말 둘은 그리지 않는다 — 벡터 탈것 리그(render/mounts.js) 재사용 (명세 §2 '말 그리기'). 탈것 채색 퍼핏도 없다.
// 상한 20장 · 40크레딧 (재시도 포함, 보스 + 초상화 둘). 계획 11장 · 22크레딧:
//   ch_portrait 2 · mg_portrait 2 · ch_coachman 2 · ch_limbs 1 · ch_coach 2 · ch_heads 1 · ch_props 1
//   (명세 표의 ch_seated(앉은 상반신)는 ch_limbs(팔·다리 조각)로 바꿨다 — 앉은 자세는 관절 다리(허벅지·정강이)로 만들고,
//    ex4 의 교훈(옆모습 전신은 팔 없이 깔끔하게, 팔은 따로)대로 팔 조각이 필요하다. 장 수·크레딧은 같다.)
// 결과(생성 ID·채택/기각 이유)는 tools/kling/manifest_ex5-boss.json 과 configs/b_charon.json 의 kling 블록에 기록한다.
// 사용: node tools/painted/prompts/ex5-boss.mjs [shotId]  → 프롬프트 출력 (Kling 호출은 에이전트가 MCP 로 한다)

export const SUFFIX = 'Flat uniform plain mid-grey studio background (#808080), no gradient, no floor, no cast shadow on the background. Strong key light from the upper left, darker lower right, crisp readable silhouette. Isolated object, nothing else in the image, no text, no labels.';
const NOFX = 'No smoke, no mist, no fire, no sparks, no particles, no floating embers, no glow haze, no magic effects around the object.';
const NOHALO = 'No glowing outline, no light halo and no bright rim around the silhouette; the object edge meets the flat grey background directly.';
const BOSS_TAIL = 'Dark gothic horror boss concept art, elegant yet menacing and grotesque, highly detailed painterly digital illustration, dramatic lighting, dark background, video game boss portrait, a single character, no text, no watermark.';
const MOUNT_TAIL = 'Dark gothic fantasy creature portrait, highly detailed painterly digital illustration, dramatic rim lighting, dark atmospheric background with pale dawn light, video game companion card art, no text, no letters, no watermark.';

const CH = 'Paint in exactly the same painterly dark-fantasy oil-painting style as 图片1: soft visible brush strokes, black lacquer and worn black wool, tarnished gold leaf, ash-grey dead skin, cold teal-green soul-fire light, no black outlines, not cartoon, not cel-shaded, not anime, not 3D render. Game asset for a 2D cut-out puppet.';
const MAN = 'The coachman is the same man as in 图片1: very tall and gaunt, a gaunt skull-like ash-grey face with deep hollow eye sockets glowing teal-green, lank black hair, a tall black top hat with a dark red band and a small brass buckle, a long black caped coachman\'s greatcoat with a layered shoulder cape, brass buttons and a dark green lining, black leather gloves, tall black riding boots.';   // ch_portrait #2 (채택본) 에 맞춰 고침 — 해골 같은 잿빛 얼굴 · 붉은 띠 모자

/** shot → { tool, aspect, count, refs (image_1 = 카론 초상화), prompt } */
export const SHOTS = {
  ch_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Charon, the coachman of Death, a very tall gaunt undead coachman of a hearse, ash-grey dead skin, deep sunken hollow eyes with faint teal-green pinpoints of light, a weary courteous expression, a tall black top hat wrapped with a black mourning crape band whose long ends trail behind, a long black caped coachman's greatcoat with three layered shoulder capes and tarnished gold buttons, black leather gloves, one hand raising an old iron carriage lantern burning with ghostly teal-green soul fire, the other hand holding a long coachman's whip, seen in three-quarter view, standing beside a black lacquered hearse carriage with gold-leaf trim, glass windows showing a coffin and more coffins strapped on its roof, behind them a burning ranch stable and charred fences under a huge blood-red moon at night. ${BOSS_TAIL}` },
  mg_portrait: { tool: 'text_to_image', aspect: '3:4', count: 2, refs: [], prompt: `Morgen, the spectral warhorse of the knights of the Dawn Oath, a noble pearl-white ghostly warhorse with a softly luminous coat, a white steel chanfron face plate and a white steel breastplate embossed with a golden rising-sun crest, a white and gold saddle cloth, a long flowing mane and tail of white-gold flickering flame, gentle kind dark eyes, no rider, standing proudly in a scorched burnt ranch at dawn with charred fence posts and a ruined stable behind it, the first pale golden light of sunrise on the horizon, a few motes of light drifting up from its mane. ${MOUNT_TAIL}` },

  ch_coachman: { tool: 'image_to_image', aspect: '9:16', count: 2, refs: ['portrait'], prompt: `${CH} ${MAN} Strict side view (profile) facing RIGHT, his nose points to the right edge of the image, of the whole body of the tall coachman from 图片1 WITHOUT ARMS: both arms are completely missing, the layered shoulder capes hang down over the shoulders and end cleanly, so the whole side of the buttoned greatcoat is visible. The full figure standing upright from the top of the tall top hat to the boots: the long greatcoat closed and reaching below the knees with its back skirt hanging behind, black trousers, tall black riding boots, both legs straight and slightly apart. No hands, no lantern, no whip, no white border, no sticker outline. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ch_limbs: { tool: 'image_to_image', aspect: '16:9', count: 1, refs: ['portrait'], prompt: `${CH} ${MAN} Six separate pieces of the coachman from 图片1 laid out apart from each other in two rows with wide empty space between them, no piece touches another, each lying straight and horizontal and pointing right, no person, no body, no head: top row: 1) an upper arm in a black wool greatcoat sleeve, from the rounded shoulder on the left to the elbow on the right; 2) a forearm in the same black sleeve with a turned-back cuff, ending in a black leather gloved hand clenched in a tight fist around an empty round hole as if gripping a pole; 3) the same kind of forearm ending in an open black gloved hand with the fingers curled as if holding a lantern ring; bottom row: 4) a thigh in black trousers from the hip on the left to the knee on the right; 5) a shin in a tall black leather riding boot from the knee on the left to the boot sole and toe on the right; 6) the long back skirt of the black greatcoat alone, hanging flat. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ch_coach: { tool: 'image_to_image', aspect: '16:9', count: 2, refs: ['portrait'], prompt: `${CH} Strict side view (profile) of the black hearse carriage from 图片1 WITHOUT HORSES and WITHOUT DRIVER, its front pointing to the RIGHT edge of the image: a long black lacquered coffin-shaped wooden box body on a low chassis with tarnished gold-leaf trim and carved gold ornaments, a large glass side window showing a dark coffin inside, several plain wooden coffins strapped on the roof behind a low black iron roof rail, an empty high coachman's box seat at the front top right with a footboard, two old iron carriage lanterns with teal-green glass mounted at the front corners, two large black spoked wooden wheels with iron rims (the rear wheel larger), two long thin wooden carriage shafts sticking straight out to the right from the front at axle height. The whole carriage fits inside the image with empty margin at both ends. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ch_heads: { tool: 'image_to_image', aspect: '4:3', count: 1, refs: ['portrait'], prompt: `${CH} ${MAN} Three separate pieces side by side in one row with wide empty space between them, all in strict side view (profile) facing RIGHT (every nose points to the right edge of the image), the same scale, no body: 1) on the left, the head of the coachman from 图片1 wearing the tall black top hat with its dark red band, cut cleanly at the base of the neck above a high black collar; 2) in the middle, the same gaunt ash-grey head WITHOUT the hat, thin lank grey hair, deep sunken eyes, cut cleanly at the base of the neck; 3) on the right, the tall black top hat alone with its dark red band and small brass buckle, seen from the side. ${NOFX} ${NOHALO} ${SUFFIX}` },
  ch_props: { tool: 'image_to_image', aspect: '1:1', count: 1, refs: ['portrait'], prompt: `${CH} About nine separate objects belonging to the hearse coachman from 图片1 arranged in a loose grid with wide empty space between them, no piece touches another: an old iron carriage lantern with teal-green glass seen from the side with its hanging ring on top, a plain dark wooden coffin seen from the side lying horizontal, one large black spoked wooden carriage wheel with an iron rim seen flat from the side, the handle of a coachman's whip lying straight and horizontal, a short straight piece of snapped black leather reins with a few iron chain links, a single tarnished silver coin seen flat, a thick old ledger book with burnt edges, and two jagged broken pieces of black lacquered wood with gold trim. ${NOFX} ${NOHALO} ${SUFFIX}` },
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  for (const [k, s] of Object.entries(SHOTS)) if (!id || id === k) console.log(`── ${k} (${s.tool} ${s.aspect} ×${s.count})\n${s.prompt}\n`);
}
